### ISSUE TITLE
Change font used by diff-hl?

### ISSUE THREAD

**Issue by sondr3** [dgutov/diff-hl#101]
Hello, this is probably a bit of a dumb question but I'm using org-mode with a variable pitch font (proportional font) and since it's not monospaced you end up with some of the signs being truncated in the margin (I use `diff-hl-margin-mode`), I'd like to change the font used by diff-hl to the monospaced one, but haven't been able to figure this out from looking at the source. Is there a way to do this?

Thanks in advance 😄

**Comment by dgutov** [comment]
Have you tried customizing the `diff-hl-margin-...` faces?

**Comment by sondr3** [comment]
Nope, I haven't really customised any faces yet. Do I just redefine them and use them or do I make my own and inherit the base ones?

**Comment by dgutov** [comment]
Try `M-x customize-face`. :)

**Comment by sondr3** [comment]
Thanks, I'll figure it out :)
