### ISSUE TITLE
Running svn failed.

### ISSUE THREAD

**Issue by tszg** [dgutov/diff-hl#113]
Using diff-hl to manage svn projects in `Windows` environment will result in an error:
`Running SVN --non-interactive diff --diff-cmd= diff-x-u0 Gemfile...FAILED (1) the status`

**Comment by dgutov** [comment]
Sorry, I don't have a Windows machine handy.

If you manage to debug this and figure out what's going wrong, please tell.

**Comment by tszg** [comment]
I don't know how to debug, but I run `SVN --non-interactive diff --diff-cmd= diff-x-u0 Gemfile` in Windows cmd and return
`SVN: E720002: Can't start process 'diff': the system Can't find the specified file.`
Then I try to use `SVN --non-interactive diff Gemfile`, and he returns the comparison for success.

**Comment by dgutov** [comment]
Oh. You need to download `diff.exe` and put it somewhere in PATH.

**Comment by tszg** [comment]
Thank you.
