### ISSUE TITLE
Flydiff makes lots of unnecessary calls to diff

### ISSUE THREAD

**Issue by ermingol23** [dgutov/diff-hl#114]
For some reason I had messed up something with modules command (and dependencies between modules) with the side effect that each call to the diff command took 3-10 seconds. This in turn resulted in that moving the cursor around in the buffer got really slow when flydiff-mode was activated since each movement resulted in the diff command being called...

Investigating this issue lead me to that there are lots of unnecessary calls to diff, that is an already diffed file with no additional changes got diffed several times. Or that when saving a buffer the diff command is called when flydiff-mode is activated and so on. Below is a proposed fix for this issue (unfortunately I am not able to send you any pull request, but this should hopefully be ok since the necessary changes are minor).

All changes below are for **diff-hl-flydiff.el**.

Replace
`(defvar diff-hl-flydiff-modified-tick 0)`
and
`(make-variable-buffer-local 'diff-hl-flydiff-modified-tick)`
with
`(defvar-local diff-hl-flydiff-modified-tick nil)`

Remove the line
`(setq diff-hl-flydiff-modified-tick (buffer-modified-tick))`
from function diff-hl-flydiff-buffer-with-head.

    (defun diff-hl-flydiff-update (orig-fun)
      "Update diff markings if buffer has been modified since last call.
    
    Calls ORIG-FUN only when buffer has been modified since last
    call, buffer exists as a file, and it is not a remote file."
      (when (and diff-hl-mode
                 (diff-hl-flydiff/modified-p)
                 (stringp buffer-file-name)
                 (file-exists-p buffer-file-name)
                 (not (file-remote-p default-directory)))
        (apply orig-fun nil)))
    
    (defun diff-hl-flydiff/modified-p (&optional state)
      "Return t if buffer modified since last call, otherwise nil.
    
    Argument STATE is ignored."
      (let ((state (not (eq diff-hl-flydiff-modified-tick
                            (buffer-chars-modified-tick)))))
        (if state
          (setq diff-hl-flydiff-modified-tick (buffer-chars-modified-tick)))
        state))
    
    (define-minor-mode diff-hl-flydiff-mode
      "Perform highlighting on the fly..."
      (if diff-hl-flydiff-mode
        (progn
          ;; Ensure current diff state is shown when mode is enabled.
          (setq diff-hl-flydiff-modified-tick nil)
          ...
          (advice-add 'diff-hl-update :around
                    #'diff-hl-flydiff-update)
          (setq diff-hl-flydiff-timer
                (run-with-idle-timer diff-hl-flydiff-delay t #'diff-hl-update)))
    
        (advice-remove 'diff-hl-update #'diff-hl-flydiff-update)
    ...
    )

**Comment by dgutov** [comment]
Hi!

I don't think we can move the modified-tick check into `diff-hl-flydiff/modified-p` because then `diff-hl-changes` would go ahead anyway, see "zero changes" and remove all the overlays before the flydiff timer works and puts then on again.

Anyway, I'm not seeing the extra calls you're referring to. How does one reproduce that? Please start with `emacs -Q -L ~/.emacs.d/elpa/diff-hl-*/ --eval "(require 'diff-hl)" --eval "(require 'diff-hl-flydiff)"`.

And to trace the calls, try:

```diff
diff --git a/diff-hl-flydiff.el b/diff-hl-flydiff.el
index 33cbfbd..c0bae20 100644
--- a/diff-hl-flydiff.el
+++ b/diff-hl-flydiff.el
@@ -125,6 +125,8 @@ This requires the external program `diff' to be in your `exec-path'."
   (interactive)
   (vc-ensure-vc-buffer)
   (setq diff-hl-flydiff-modified-tick (buffer-modified-tick))
+  (message "setting diff-hl-flydiff-modified-tick to %s and calling diff"
+           diff-hl-flydiff-modified-tick)
   (save-current-buffer
     (let* ((temporary-file-directory
             (if (file-directory-p "/dev/shm/")
@@ -144,6 +146,9 @@ This requires the external program `diff' to be in your `exec-path'."
            (not buffer-file-name)
            (not (file-exists-p buffer-file-name))
            (file-remote-p default-directory))
+    (message "updating %S in %s %s %s" (gensym) (current-buffer)
+             diff-hl-flydiff-modified-tick
+             (buffer-modified-tick))
     (diff-hl-update)))
 
 (defun diff-hl-flydiff/modified-p (state)
diff --git a/diff-hl.el b/diff-hl.el
index 5ef4f88..3586295 100644
--- a/diff-hl.el
+++ b/diff-hl.el
@@ -245,6 +245,7 @@ the end position as its only argument."
 
 (defun diff-hl-changes-buffer (file backend)
   (let ((buf-name " *diff-hl* "))
+    (message "shouldn't see this!")
     (diff-hl-with-diff-switches
      ;; FIXME: To diff against the staging area, call 'git diff-files -p'.
      (vc-call-backend backend 'diff (list file)
```

**Comment by ermingol23** [comment]
The core issue is that the current code calls `(buffer-modified-tick)` instead of `(buffer-chars-modified-tick`. This in turn leads to `(diff-hl-update)` being called when it was not supposed to be called.

Furthermore, there are hooks defined in diff-hl.el (for instance one that is run every time a buffer is saved) that checks against whether the buffer has been modified or not by calling `buffer-modified-p` instead of using a check based on `(buffer-chars-modified-tick)`. This thus results in `diff-hl-update` being called every time the buffer is saved regardless of if something has been changed in the buffer since the last time `diff-hl-update` was called or not. In order to avoid this I defined an advice for `diff-hl-update` that checks if buffer has been modified or not since the last call.

I might have misunderstood you comment about 'zero-changes', but I changed the default value for `diff-hl-flydiff-modified-tick` to **nil** instead of **0** (zero) in order to catch the case when `diff-hl-flydiff-modified-tick` had not yet been updated (since zero is a valid value that can be returned from `(buffer-chars-modified-tick)`). After that point I compare against the previous value of `(buffer-chars-modified-tick)` and if nothing has been changed in the buffer the value returned is stable (which is not the case when calling `(buffer-modified-tick)`). I experienced getting different values returned from `(buffer-modified-tick)` when moving the cursor on to and off from a row containg changes (as well as when moving the cursor forward and backward on such a changed row). This did not happen when calling `(buffer-chars-modified-tick)`.

The elisp documentation for _buffer-**chars**-modified-tick_ states
> This function returns buffer's character-change modification-count. Changes to text properties leave this counter unchanged; however, each time text is inserted or removed from the buffer, the counter is reset to the value that would be returned by buffer-modified-tick. By comparing the values returned by two buffer-chars-modified-tick calls, you can tell whether a character change occurred in that buffer in between the calls. If buffer is nil (or omitted), the current buffer is used. 

BTW. I'll try and  apply your patch to an unmodified verision of diff-hl and report back the result.

**Comment by dgutov** [comment]
> I might have misunderstood you comment about 'zero-changes'

I meant "no changes". As in, no chunks to highlight.

> The core issue is that the current code calls (buffer-modified-tick) instead of (buffer-chars-modified-tick

If that's the only problem, does replacing both calls to `buffer-modified-tick` with `buffer-chars-modified-tick` fix the misbehavior you're seeing?

**Comment by ermingol23** [comment]
> If that's the only problem, does replacing both calls to buffer-modified-tick with buffer-chars-modified-tick fix the misbehavior you're seeing?

It is a two-pronged problem. This fixes one part of the problem. The other part is that in diff-hl-flydiff.el 

    (defun diff-hl-flydiff-update ()
      (unless (or
               (not diff-hl-mode)
               (= diff-hl-flydiff-modified-tick (buffer-modified-tick))
               (not buffer-file-name)
               (not (file-exists-p buffer-file-name))
               (file-remote-p default-directory))
        (diff-hl-update)))

the variable `diff-hl-flydiff-modified-tick` is only updated in `diff-hl-flydiff-buffer-with-head`. You also need to update it within the `(unless ...)` so you get something like this

    (defun diff-hl-flydiff-update ()
      (unless (or
               (not diff-hl-mode)
               (= diff-hl-flydiff-modified-tick (buffer-chars-modified-tick))
               (not buffer-file-name)
               (not (file-exists-p buffer-file-name))
               (file-remote-p default-directory))
        (setq diff-hl-flydiff-modified-tick (buffer-chars-modified-tick))
        (diff-hl-update)))

And then there is the final twist to it; the initial value of `diff-hl-flydiff-modified-tick` can not be `0` since that is a valid value returned from `(buffer-chars-modified-tick)`. Instead you might use `nil` as I suggested as the default initial value for this variable, i.e. change `(defvar diff-hl-flydiff-modified-tick 0)` to `(defvar diff-hl-flydiff-modified-tick nil)`. This is to guarantee that the diff program is called after initial loading of a file (there is a very small probability that `(buffer-chars-modified-tick)` returns `0` after initial load of a file).

**Comment by dgutov** [comment]
> You also need to update it within the (unless ...) so you get something like this

Why? If every call to fetch the list of hunks goes through setting this variable (no matter if the call is initiated by the timer or the after-save-hook), the `diff-hl-flydiff-update` check will do its job anyway.

So I'd like to know the exact scenario where you see the unnecessary calls. Some tracing as well, maybe.

As for the other two changes, I'll push them now, thank you.

> This is to guarantee that the diff program is called after initial loading of a file

It will be called anyway because `diff-hl-update` is in `find-file-hook`, but ok.

**Comment by ermingol23** [comment]
I have now tested with an unmodified diff-hl with the patch you suggested and started emacs 26.1 with

    emacs -Q -L ~/.emacs.d/elpa/diff-hl-*/ --eval "(require 'diff-hl)" --eval "(require 'diff-hl-flydiff)"
    
After enabling diff-hl like this in the scratch-buffer

    (global-diff-hl-mode)<C-j>
    t
    (diff-hl-flydiff-mode)<C-j>
    t

I split the scracth-buffer with <C-x 3> and in the right window I swicth to Messages-buffer and in the left window I open a file that is under git version control (diff-hl-flydiff.el). The left window is the active window. Each time I move the cursor up, down, left or right I get a message printed in Messages-buffer. I get something like this

    updating g0 in diff-hl-flydiff.el 0 92
    updating g1 in diff-hl-flydiff.el 0 92
    updating g2 in diff-hl-flydiff.el 0 92
    updating g3 in diff-hl-flydiff.el 0 92
    updating g4 in diff-hl-flydiff.el 0 92
    updating g5 in diff-hl-flydiff.el 0 92
    updating g6 in diff-hl-flydiff.el 0 92
    updating g7 in diff-hl-flydiff.el 0 92
    updating g8 in diff-hl-flydiff.el 0 92
    updating g9 in diff-hl-flydiff.el 0 92
    updating g10 in diff-hl-flydiff.el 0 92
    updating g11 in diff-hl-flydiff.el 0 92
    ...

Then I applied my suggested modification to `diff-hl-flydiff-update`. While doing so I noticed a changed behavior in the printouts in Messages-buffer; each character typed resulted in a printout as well as the first movement left, right, up, or down after typing a character plus the first time I entered the changed area after moving outside of it.

**Comment by dgutov** [comment]
I can't reproduce the scenario you're describing. Only get "updating" after making actual changes to the buffer text.

First of all, which version exactly did you apply to patch to? It does not apply cleanly to the current master.

Second, you might probably want to replace the `(buffer-modified-tick)` calls with `(buffer-chars-modified-tick)` in the print-debugging code.

Third and the most important: if `diff` is called, where are all the `setting diff-hl-flydiff-modified-tick to %s and calling diff` messages? Did you just omit them from the copy?

**Comment by ermingol23** [comment]
I realized that I made some mistake when patching. :(
After patching correctly I get this behavior when loading a git-version-controlled file into a new buffer
 and typing something.

    setting diff-hl-flydiff-modified-tick to 1 and calling diff
    updating g0 in diff-hl-flydiff.el 93 93
    setting diff-hl-flydiff-modified-tick to 93 and calling diff
    updating g0 in diff-hl-flydiff.el 132 132
    setting diff-hl-flydiff-modified-tick to 173 and calling diff
    updating g0 in diff-hl-flydiff.el 173 173
...

No messages when just moving cursor around.

I redid the experiment and added the same printouts to my proposed patch and got exactly the same behavior.

So I have to admit I was partly very wrong. :) It should suffice to just use (buffer-chars-modified-tick) instead of (buffer-modified-tick).

**Note:** The version of diff-hl I currently use is what was on master 11th of July 2018 (10:34 GMT+2).

**Comment by ermingol23** [comment]
Made mistake when replicating the messages in Messages buffer. It should be `g0`, `g1`, `g2`, and so on.

**Comment by dgutov** [comment]
So is everything in order now?

**Comment by ermingol23** [comment]
Yes, as far as I can tell. So you can close this issue. :)
