### ISSUE TITLE
Error running timer wrong-type-argument

### ISSUE THREAD

**Issue by concavegit** [dgutov/diff-hl#115]
Hello, after commit 7144c1c3c346017a90642340747598e0e883aded I get this error message when moving my cursor around in any file:
```
Error running timer ‘diff-hl-flydiff-update’: (wrong-type-argument number-or-marker-p nil)
```

I fixed that issue by reverting the [first line](https://github.com/dgutov/diff-hl/commit/7144c1c3c346017a90642340747598e0e883aded#diff-17dc9731ec62fb0634784c64a9d9dd89L41) to how it was.

``` emacs-lisp
(defvar diff-hl-flydiff-modified-tick 0)
```
 Is that how it should have been fixed?

**Comment by dgutov** [comment]
Ouch, thanks for reporting. Should be fixed now.
