### ISSUE TITLE
Customizable fringe bitmap?

### ISSUE THREAD

**Issue by jrosdahl** [dgutov/diff-hl#116]
Thanks for diff-hl!

Would you be interested in opening up for different fringe bitmap styles, or some other way of making the fringe bitmap customizable?

Background: I think that a vertical bar fringe indicator looks nicer than the default diff-hl look, so I made a small modification to diff-hl to accomplish that (see jrosdahl/diff-hl@cc23bb735ebcefb5df35f50913862eccbef00053). Maybe it would a good idea to introduce a fixed list of fringe bitmap styles to choose from, or maybe a hook that diff-hl-define-bitmaps can call in some way (don't know how)? I'm happy to keep my change as a fork of course, just wanted to know if you think that it should stay that way or if it's something worth considering making more generic for inclusion in diff-hl.

By the way, here's an indication of how it looks after my modification:

![diff-hl-bars](https://user-images.githubusercontent.com/146927/50307763-8f2b5580-0499-11e9-9f53-4f82de2e3eec.png)

**Comment by dgutov** [comment]
There's a user option called `diff-hl-fringe-bmp-function`. You can set it to a function of your choice that returns the same bitmap here, that you define in your init script.

**Comment by dgutov** [comment]
> if it's something worth considering making more generic for inclusion in diff-hl

Maybe. The patch you linked to won't work for that, of course.

**Comment by jrosdahl** [comment]
> There's a user option called diff-hl-fringe-bmp-function. You can set it to a function of your choice that returns the same bitmap here, that you define in your init script.

Thanks. I obviously missed that option, not really sure why. Perhaps partly because I didn't expect it and partly because it's not mentioned in the README or the package commentary.

Closing the issue since it solves my use case nicely. For the record, here's what I ended up using:

```elisp
  (let* ((height (frame-char-height))
         (width 2)
         (ones (1- (expt 2 width)))
         (bits (make-vector height ones)))
    (define-fringe-bitmap 'my-diff-hl-bitmap bits height width))
  (setq diff-hl-fringe-bmp-function (lambda (type pos) 'my-diff-hl-bitmap))
```

(To fully replicate my setup, the background of the `diff-hl-*` faces needs be set to the same color as the fringe as well.)

Feel free to use this as an example customization if you like, or to just let it pass into oblivion.

> The patch you linked to won't work for that, of course.

I'm a bit surprised that you felt a need to point that out. :wink:

**Comment by dgutov** [comment]
> it's not mentioned in the README or the package commentary

I wasn't sure if there's going to be a lot of demand, or how and where to document it best. If you'd like to give it a try, please go ahead.

> Feel free to use this as an example customization if you like

Not sure where to put it that kind of example, since we don't have an extensive kind of documentation here (like a manual). I can open the wiki for writing, if you like.

**Comment by aguynamedben** [comment]
Here's what me and ChatGPT came up with

```elisp
;; Highlight uncommitted changes using VC
(use-package diff-hl
  :init
  (global-diff-hl-mode)
  :hook
  ;; Magit hooks
  ;; https://github.com/dgutov/diff-hl#magit
  (magit-pre-refresh . diff-hl-magit-pre-refresh)
  (magit-post-refresh . diff-hl-magit-post-refresh)
  :config
  ;; Configure the fringe (built-in) for diff-hl
  (defun my-minimalist-fringe ()
    "Minimal fringe setup, courtesy ChatGPT"
    (message "Configuring minimalist fringe...")
    ;; Set fringe width to 1 pixel
    (fringe-mode 1)
    ;; Set fringe background color to match the window background
    (set-face-attribute 'fringe nil :background (face-background 'default))
    ;; Set fringe bitmap function to a minimal representation
    (setq diff-hl-fringe-bmp-function 'diff-hl-fringe-bmp-from-type)
    ;; Adjust fringe indicator width
    (setq-default left-fringe-width 4)
    (setq-default right-fringe-width 4)
    ;; Hide left and right fringes when they are empty
    (setq indicate-buffer-boundaries nil)
    (setq indicate-empty-lines nil)
    (setq-default fringe-indicator-alist
                  '((truncation . nil)
                    (continuation . nil)))
    (message "\tDone"))
  (my-minimalist-fringe))
```

**Comment by dgutov** [comment]
@aguynamedben Alas, the generated snippet is mostly unrelated settings. Nor does it generate a new fringe bitmap (which this issue was about, I think).

The only relevant line is the one with `diff-hl-fringe-bmp-function`, but it sets that to an existing function, rather than create a "custom" one.

**Comment by aguynamedben** [comment]
@dgutov Sorry for creating noise 😬 I think I had like 10 tabs open about "how do I make a minimalist fringe with dff-hl" and over-excitedly shared my solution thinking it'd be valuable for others stumbling around Google/GitHub. Feel free to delete if too off topic.

**Comment by aguynamedben** [comment]
Also thank you for providing diff-hl, I'm loving it 🙏

**Comment by nick4f42** [comment]
I slightly modified @jrosdahl's code to remove the dependence on `(frame-char-height)` so there won't be gaps if you use emacs daemon or resize the font. It uses the `PERIODIC` argument of `define-fringe-bitmap`:

```elisp
(let* ((width 2)
       (bitmap (vector (1- (expt 2 width)))))
  (define-fringe-bitmap 'my:diff-hl-bitmap bitmap 1 width '(top t)))
(setq diff-hl-fringe-bmp-function (lambda (type pos) 'my:diff-hl-bitmap))
```

Make sure the `diff-hl-*` face backgrounds aren't the same color.

**Comment by Schievel1** [comment]
I don't understand this. I use the examples from this issue, but the bars in the fringe are always as wide as the fringe. 
I am on emacs 30.2, did something change regarding this in the meantime?

Here's my use-package block for diff-hl at the moment:
```
(use-package diff-hl
  :config
  (global-diff-hl-mode)
  (setq diff-hl-disable-on-remote t)
  ;; (setq diff-hl-draw-borders nil)
  (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh)
(let* ((width 2)
       (bitmap (vector (1- (expt 2 width)))))
  (define-fringe-bitmap 'my:diff-hl-bitmap bitmap 1 width '(top t)))
(setq diff-hl-fringe-bmp-function (lambda (type pos) 'my:diff-hl-bitmap)))

```

**Comment by dgutov** [comment]
@Schievel1 You probably missed this line in the description of the solution:

> (To fully replicate my setup, the background of the diff-hl-* faces needs be set to the same color as the fringe as well.)

**Comment by Schievel1** [comment]
Yes I did. Sorry for that.
