### ISSUE TITLE
fails when there are no commits

### ISSUE THREAD

**Issue by nolanwrightdev** [dgutov/diff-hl#117]
Hi,

I just started trying to use this package, and I noticed an issue in the case where a git repository is initialized but has no commits. In this case, whenever I try to open a staged file, I get the following error.

`Running git --no-pager diff-index --exit-code -U0 -p HEAD  -- init-use-package.el...FAILED (status 128)`

Executing that command in the shell results in `fatal: bad revision 'HEAD'`. And for reference `git log` results in `fatal: your current branch 'master' does not have any commits yet`.

The annoying bit is that this issue blocks my files from being opened.

The relevant parts of my config:
```
(use-package magit
  :bind
  ("C-c g" . magit-status))

(use-package diff-hl
  :init
  (global-diff-hl-mode)
  :hook
  (magit-post-refresh . diff-hl-magit-post-refresh)
  (dired-mode . diff-hl-dired-mode))
```

It works perfectly fine, so far as I can tell, in repositories with commits, by the way. Perhaps the solution is simply to make a commit, but I wanted to check in nonetheless.

**Comment by professorwright** [comment]
Hm, removing that line seemed to fix the issue, and also didn't affect the functionality otherwise. Cool.

**Comment by dgutov** [comment]
Not sure you want to remove it, it's a helpful piece of Magit integration. Just something I wanted to check.

Anyway, I managed to repro the problem (stage a file, then edit and save).

**Comment by dgutov** [comment]
Here's a hack you can use:

```lisp

(defun diff-hl-changes-buffer (file backend)
  (let ((buf-name " *diff-hl* "))
    (condition-case err
        (diff-hl-with-diff-switches
         ;; FIXME: To diff against the staging area, call 'git diff-files -p'.
         (vc-call-backend backend 'diff (list file)
                          diff-hl-reference-revision nil
                          buf-name))
      (error
       (when (string-match-p "\\`Failed (status 128)" (error-message-string err))
         (diff-hl-with-diff-switches
          ;; FIXME: To diff against the staging area, call 'git diff-files -p'.
          (vc-call-backend backend 'diff (list file)
                           "4b825dc642cb6eb9a060e54bf8d69288fbee4904"
                           nil
                           buf-name)))))
    buf-name))
```

But this code is Git-specific, and ultimately it's something to be fixed in Emacs.

**Comment by dgutov** [comment]
This should be working fine since version 1.8.6.
