### ISSUE TITLE
Can I have diff-hl show diff between current code and another branch?

### ISSUE THREAD

**Issue by aguynamedben** [dgutov/diff-hl#118]
This looks awesome, thanks for making it available to everybody. I had a question... by default this highlights uncommitted changes. Is there a way I can have it instead diff changes that are in my current code that deviate from the `master` branch?

My workflow:
* Create a `my-branch` branch from the `master` branch.
* Code, commit, code, commit, etc.
* Now I want diff-hl to show based on a diff of `my-branch` and `master` (not just uncommitted changes). For larger multi-stage projects, that would really help give an idea of the working set of changes I'm working with.

Is this easy? Thanks again for providing this great library.

**Comment by dgutov** [comment]
Try setting `diff-hl-reference-revision` to that branch's name.
