### ISSUE TITLE
How to auto-enable diff-hl in .emacs

### ISSUE THREAD

**Issue by qohelet** [dgutov/diff-hl#122]
I like to work with diff-hl but find it a little disturbing to set it on every buffer again. Is there a way to auto-enable it in the .emacs?

Seems someone [asked that already](https://github.com/dgutov/diff-hl/issues/21), but there isn't any useful answer yet.

**Comment by dgutov** [comment]
See `M-x describe-package RET diff-hl RET`.

**Comment by qohelet** [comment]
How is this helpful?

    diff-hl is an installed package.

     Status: Installed in ‘diff-hl-20190128.201/’ (unsigned). Delete
    Version: 20190128.201
    Summary: Highlight uncommitted changes using VC
    Requires: cl-lib-0.2, emacs-24.3
    Homepage: https://github.com/dgutov/diff-hl
    Keywords: vc diff 
    Other versions: 20190128.201 (melpa), 1.8.5 (gnu).

**Comment by dgutov** [comment]
That's odd. Here's how it looks here:

```
Package diff-hl is installed.

     Status: Installed in ‘diff-hl-20190128.201/’ (unsigned). Delete
    Version: 20190128.201
    Summary: Highlight uncommitted changes using VC
   Requires: cl-lib-0.2, emacs-24.3
   Homepage: https://github.com/dgutov/diff-hl
   Keywords: vc diff 
Other versions: 20190128.201 (melpa), 1.8.5 (gnu).


`diff-hl-mode' highlights uncommitted changes on the side of the
window (using the fringe, by default), allows you to jump between
the hunks and revert them selectively.

Provided commands:

`diff-hl-diff-goto-hunk'  C-x v =
`diff-hl-revert-hunk'     C-x v n
`diff-hl-previous-hunk'   C-x v [
`diff-hl-next-hunk'       C-x v ]

The mode takes advantage of `smartrep' if it is installed.

Add either of the following to your init file.

To use it in all buffers:

(global-diff-hl-mode)

Only in `prog-mode' buffers, with `vc-dir' integration:

(add-hook 'prog-mode-hook 'turn-on-diff-hl-mode)
(add-hook 'vc-dir-mode-hook 'turn-on-diff-hl-mode)

[back]
```

**Comment by dgutov** [comment]
What's your Emacs version?

**Comment by qohelet** [comment]
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2018-05-29

**Comment by dgutov** [comment]
OK, my bad. Support for showing descriptions for already installed packages was only added in Emacs 27 (still not released).

To be fair, README says this "Check out the Commentary section in each respective file for the usage instructions". And the Commentary in `diff-hl.el` has everything necessary.

I agree it could be more helpful, though.
