### ISSUE TITLE
diff-hl-flydiff-delay not in diff-hl-flydiff custom group

### ISSUE THREAD

**Issue by ermingol23** [dgutov/diff-hl#123]
The definition of the custom parameter `diff-hl-flydiff-delay` does not assign it to any customization group, i.e. change from

```
(defcustom diff-hl-flydiff-delay 0.3
  "The idle delay in seconds before highlighting is updated."
  :type 'number)
```
to
```
(defcustom diff-hl-flydiff-delay 0.3
  "The idle delay in seconds before highlighting is updated."
  :type 'number
  :group 'diff-hl-flydiff)
```

**Comment by dgutov** [comment]
Actually, `:group` is optional. It defaults to the last group defined in the file.

`M-x customize-group RET diff-hl-flydiff RET` should show this variable. Doesn't it?

**Comment by ermingol23** [comment]
No. That was why I thought the missing “:group” mattered. But I can see it if I explicitly choose to customize the variable diff-hl-flydiff-delay.

**Comment by dgutov** [comment]
> No.

Weird. I do see it there.

Do you have a step-by-step repro? Preferably with a screenshot of the Customize buffer.

**Comment by ermingol23** [comment]
Hmmm. Most likely it is something with my configuration. You can close this issue and if I find something when investigating on my end I’ll raise a new issue.
