### ISSUE TITLE
Command to show diff of current hunk

### ISSUE THREAD

**Issue by m-cat** [dgutov/diff-hl#126]
Is there a way to do as the title states? I currently do this by calling `diff-hl-revert-hunk` which shows the diff and asks for confirmation, but I'm not able to navigate around in the buffer, so it's not very useful for large diffs.

**Comment by iquiw** [comment]
<kbd>C-x v =</kbd> `diff-hl-diff-goto-hunk` ?

**Comment by m-cat** [comment]
Missed that somehow, thanks!
