### ISSUE TITLE
Disabling diff-hl-margin-minor-mode while it is already disabled breaks diff-hl-highlight-function

### ISSUE THREAD

**Issue by fpiper** [dgutov/diff-hl#128]
Basic steps to reproduce:
* run `diff-hl-mode` with fringe indicator (so `diff-hl-margin-minor-mode` is off)
* eval `(diff-hl-margin-minor-mode 0)` to disable margin-mode
* any update to the diff highlights now removes all of them

https://github.com/dgutov/diff-hl/blob/374b1d4b34876219218da7a539e7301259b56958/diff-hl-margin.el#L115-L116
This code globally sets `diff-hl-highlight-function` to `diff-hl-margin-old-highlight-function`. But as margin-minor-mode was never enabled, this variable was never set. So this globally sets `diff-hl-highlight-function` to `nil`, breaking all fringe indicators.
There should probably be some kind of check if `diff-hl-old-highlight-function` is non-`nil`.

I ran into this issue while changing my theme with the customize interface `M-x customize-themes`. When changing the theme this resets all minor mode values to their current value.

**Comment by dgutov** [comment]
Hmm.

**Comment by dgutov** [comment]
Thanks for the report. Should be fixed now.
