### ISSUE TITLE
`diff-hl-amend-mode` doesn't work well with `diff-hl-flydiff mode`

### ISSUE THREAD

**Issue by AmaiKinono** [dgutov/diff-hl#131]
Here's my config:

``` emacs-lisp
(use-package diff-hl
  :config
  (global-diff-hl-mode)
  (global-diff-hl-amend-mode)
  (diff-hl-margin-mode))
```

I tested using a newly created repo, just a single file in it. The first commit is:

```
This is a line
This is another line
```

The second commit adds a line in between:

```
This is a line
A line between!
This is another line
```

Now add another line and save, `diff-hl` shows this:

![without-flydiff](https://user-images.githubusercontent.com/28714352/71083002-0559b980-21cd-11ea-9f56-9f2b6f6cfebf.png)

Now turn on `diff-hl-flydiff-mode`, it shows this:

![with-flydiff](https://user-images.githubusercontent.com/28714352/71083089-320dd100-21cd-11ea-9d48-ac586abb5f8f.png)

Notice the exclamation mark before the 2nd line has gone.

**Comment by dgutov** [comment]
Thanks for the report!

This should do it.
