### ISSUE TITLE
thick border line instead of thin

### ISSUE THREAD

**Issue by ratnesh1729** [dgutov/diff-hl#132]
(Wanted to thank first for diff-hl - this has been very useful)

![fringe_old](https://user-images.githubusercontent.com/11953515/72685780-40882a80-3aa2-11ea-8948-8d1d35217c63.png)

When I have older theme - above -> please notice that the dark border on the left - this indicates git additions.  (for info - this is gruvbox-dark--hard  from https://github.com/greduan/emacs-theme-gruvbox/blob/master/gruvbox-dark-hard-theme.el)

With the base-16 themes here - I get it like a thin line -  "please see image below" . *How can I set it similar to the one above ?*
![fringe-_base-16](https://user-images.githubusercontent.com/11953515/72685778-3d8d3a00-3aa2-11ea-8dce-a9327c32148b.png)

Best,

**Comment by dgutov** [comment]
By customizing the relevant faces. You can change the backgrounds to be lighter.

**Comment by ratnesh1729** [comment]
Thanks. A newbier here on faces or related customizations. Any more inputs for me to narrow it down.

**Comment by dgutov** [comment]
`M-x customize-group diff-hl`. There are three faces in that list.

**Comment by ratnesh1729** [comment]
Thanks!! I see now. 
So if I have to keep a customization I would like - I should put  all diff-hl faces in my init.el - and these lines will come post loading of the theme ? 
I searched themes' git page with "diff-hl"  - but could not find it ther  - I am wondering how these faces change w.r.t theme changes ?
