### ISSUE TITLE
Generalize diff-hl-amend-mode?

### ISSUE THREAD

**Issue by AmaiKinono** [dgutov/diff-hl#134]
Having this mode is great, but sometimes we want to show changes against some early version. Like when working on a PR, there are a bunch of commits and we want to see what the whole PR changes. Could we ask the user to specify the reference commit (by input a number or interactively choose from say last 15 commits)?

**Comment by dgutov** [comment]
We have a variable you can set (the same one that `diff-hl-amend-mode` uses). You could just `setq` it.

As far as adding a UI to change that var interactively... well, it should ideally be backend-agnostic. If we just ask a Git user to choose between 15 commit hashes, that wouldn't be very user-friendly.

**Comment by AmaiKinono** [comment]
Thanks. I just saw `diff-hl-reference-revision`, and that does the work.

I tried to experiment with the UI. There's a `vc-read-revision` offerd by `vc.el`, and seems we can use that. But then I found for git, it only shows tagged revisions and branches. And [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/VCS-Concepts.html#VCS-Concepts) it says:

> Each commit creates a new revision in the repository.

I don't know `vc.el` well. Do you have any idea why this happens or does it work with other VCS backends?

**Comment by dgutov** [comment]
> But then I found for git, it only shows tagged revisions and branches.

Because there is little point in completion for SHA hashes. You can paste one if you like, though. But just as well you can `(setq diff-hl-reference-revision "rev-hash")`.

> Do you have any idea why this happens

What happens? The manual just described how all version control systems work.

**Comment by AmaiKinono** [comment]
I think the manual says a "revision" means a commit in git, so I should see all commits when calling `diff-hl-reference-revision`.

> Because there is little point in completion for SHA hashes.

This makes sense. I will see if I can make use of `vc-print-log` instead.

**Comment by dgutov** [comment]
Yeah, revision and commit are the same in the context of Git.

**Comment by dgutov** [comment]
BTW, when working on a PR, you might be working against some other branch, such as `master` or `develop`. Symbolic references like that are also allowed where a revision is expected.

**Comment by dgutov** [comment]
And merged. Thanks!
