### ISSUE TITLE
diff-hl-magit-post-refresh doesn't refresh modified files after commit

### ISSUE THREAD

**Issue by afine** [dgutov/diff-hl#136]
diff-hl does not appear to automatically update buffers after I commit using magit. I need to execute `(diff-hl-update)` manually to get the desired effect.

I use diff-hl with magit and have the hook configured like so:
```elisp
(use-package diff-hl
  :after magit
  :demand
  :hook (magit-post-refresh . diff-hl-magit-post-refresh)
  :config
  (global-diff-hl-mode)
  (diff-hl-flydiff-mode))
```
I instrumented `diff-hl-magit-post-refresh` and ran through the commit process with Edebug. I noticed that the hook executes twice when going through the commit flow, once before the actual commit and once after.

On the first run, it appears that `(diff-hl-update)` is run on the appropriate buffers, but since the commit has not happened yet this does nothing.

On the second run, `(diff-hl-update)` is not run. It looks like `modified-files` (https://github.com/dgutov/diff-hl/blob/master/diff-hl.el#L597) is nil and the file is in an unmodified state.

**Comment by dgutov** [comment]
Could you report all that to Magit?

I don't use it myself, and this function has been written with significant help from @tarsius. If some Magit's inner workings have changed, that could be a bug, or even if not, that could still be fixed on Magit's side.

**Comment by afine** [comment]
Will do! Thank you.
