### ISSUE TITLE
Stopped working with recent magit 20200517.1537

### ISSUE THREAD

**Issue by pbgc** [dgutov/diff-hl#141]
Hi,

I updated to the most recent magit dev reelase (20200517.1537) yesterday and diff-hl stopped working.

Thanks

**Comment by AndreaOrru** [comment]
This is most certainly not a `diff-hl` bug. The last few revisions of `magit` are broken.

**Comment by pbgc** [comment]
@AndreaOrru I've been updating to every dev release on melpa without any problem and with diff-hl working.
This last one broke some packages because of the transient-define-prefix (https://github.com/magit/magit/issues/4117) but solvable by reinstalling the packages (I already tried that with diff-hl)

**Comment by AndreaOrru** [comment]
My bad, apologies. :) I just assumed it was due to the same issue.

**Comment by dgutov** [comment]
Same issue or not, if Magit has changed, and `diff-hl` did not, perhaps you know a better place file this report?

**Comment by pbgc** [comment]
@dgutov sure! I thought it would be nice to report, but I see it was not the case. Magit it's a lot bigger than diff-hl ... and I think they will not revert a planed change because other packages, but I will try.
Meanwhile I installed git-gutter and i'm on.
Thanks

**Comment by dgutov** [comment]
A report with some details of what changed on Magit's side would be welcome.

**Comment by AndreaOrru** [comment]
By the way, I couldn't reproduce this with the latest version of Magit and Diff-hl.

**Comment by pbgc** [comment]
@AndreaOrru I filled a issue on Magit repo ... 
I found that it only happens when using the following line (that is recommended on Magit Manual for speeding purposes):

`(setq vc-handled-backends (delq 'Git vc-handled-backends))`

**Comment by dgutov** [comment]
@pbgc Thank you for filing it. But see my comment there.

Now I feel kinda bad, BTW. I should have just asked for a proper repro. :disappointed:
