### ISSUE TITLE
margin-mode overall background

### ISSUE THREAD

**Issue by quite** [dgutov/diff-hl#144]
I'm using `diff-hl-margin-mode`. Is there a way to customize the background color for the whole margin, and not only positions with changes? I'd like the margin to stand out.

**Comment by dgutov** [comment]
Not 100% sure, but I think the margin background just uses the default face's background if nothing else is specified.

You can ask on Emacs.SE, but your best bet is probably `M-x report-emacs-bug` with a feature request.

**Comment by quite** [comment]
Aha.  Think the answer is here, but oh where is time to dig into it https://emacs.stackexchange.com/a/897

**Comment by dgutov** [comment]
Well, yeah. Adding a margin spec with an overlay on every line could do it, but honestly, it's a hack, which will slow down your Emacs (not sure by how much; perhaps imperceptibly, but still) for no good reason.

You can try it, but the feature request is really the way to go.

**Comment by quite** [comment]
There was one already: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=26909
