### ISSUE TITLE
Automatic diff-hl-margin-mode in terminal Emacs

### ISSUE THREAD

**Issue by hmenke** [dgutov/diff-hl#155]
I might be a weirdo for doing that, but I actually use both GUI and terminal Emacs on my system.  In GUI Emacs I would like to have the `diff-hl` markers in the fringe, whereas in terminal Emacs I would like to have the markers in the margin (because there is no fringe).  I thought about using the `post-command-hook` and `before-hack-local-variables-hook` to inject `diff-hl-margin-mode` depending on the value of `window-system` (I've copied this from [`emacs-direnv`](https://github.com/wbolster/emacs-direnv)).  Here is what I have right now
```elisp
(use-package diff-hl
  :ensure t
  :defer 2
  :config
  (global-diff-hl-mode)
  (dolist (it '(post-command-hook before-hack-local-variables-hook))
    (add-hook it (lambda() (diff-hl-margin-mode (window-system)))))
```
but that doesn't seem to work correctly.  Somehow this still turns on `diff-hl-margin-mode` unconditionally.  Please let me know if this is inappropriate for the issue tracker.

**Comment by dgutov** [comment]
Um.

Can you just add `(unless (window-system) (diff-hl-margin-mode))` right after `(global-diff-hl-mode)`?

**Comment by hmenke** [comment]
Thank you for the suggestion.  I'm running Emacs in daemon mode and then open buffers in both terminal and GUI clients.  This directive would only trigger once at startup and then apply to all buffers of the instance.

**Comment by dgutov** [comment]
Ah, okay. So you normally have both terminal and GUI Emacs connecting to the same daemon?

**Comment by hmenke** [comment]
Yes, that's correct.

**Comment by hmenke** [comment]
This seems to work alright, although I don't really understand why.
```elisp
(use-package diff-hl
  :ensure t
  :demand
  :config
  (global-diff-hl-mode)
  (defun user/maybe-diff-hl-margin-mode()
    (diff-hl-margin-mode (if (window-system) -1 1)))
  (dolist (it '(post-command-hook before-hack-local-variables-hook))
    (add-hook it 'user/maybe-diff-hl-margin-mode nil 1)))
```

**Comment by dgutov** [comment]
Well, you're togging it on or off in `post-command-hook`. That's bound to work, except with extra overhead of having that code run after every command you invoke. Every character typed, etc.

**Comment by dgutov** [comment]
Here's a snippet you could try instead:

```el
(add-hook 'diff-hl-mode-on-hook
          (lambda ()
            (unless (window-system)
              (diff-hl-margin-minor-mode))))
```

**Comment by hmenke** [comment]
@dgutov This doesn't work because `diff-hl-margin-minor-mode` is not autoloaded.

**Comment by dgutov** [comment]
@hmenke Good point.

I made two changes now:

* Made it autoloaded, which should resolve your complaint.
* Renamed the mode to `diff-hl-margin-local-mode`, which is more a accurate name. And updated the snippet above accordingly.
