### ISSUE TITLE
Disable magit hooks in remote file

### ISSUE THREAD

**Issue by Ergus** [dgutov/diff-hl#157]
Hi:

Is it possible to add a custom to disable the magit hooks for remote files?

**Comment by dgutov** [comment]
Hi!

Sure. Would you like to submit a patch?

**Comment by Ergus** [comment]
Hi @dgutov :
I just added #179 in reply to this. Please check it. I think that a similar approach may work for `diff-hl-dired-mode` and maybe make  `diff-hl-dired-mode-unless-remote` obsolete. So, to use a `single variable to rule them all`.

**Comment by dgutov** [comment]
Thanks, see the comments.

> I think that a similar approach may work for diff-hl-dired-mode and maybe make diff-hl-dired-mode-unless-remote obsolete

IDK, it might make sense to keep both, at least for a time.

I could imagine some low-latency but low-bandwidth connection where one would want to keep diff-hl in file buffers but not in dired.

**Comment by dgutov** [comment]
Now merged.
