### ISSUE TITLE
Don't highlight staged changes

### ISSUE THREAD

**Issue by amerov** [dgutov/diff-hl#161]
Is it possible don't handle staged changes?
Vscode and vim's Gitgutter has that behavior for example

**Comment by dgutov** [comment]
Quick question: which Emacs version do you regularly use?

**Comment by amerov** [comment]
> Quick question: which Emacs version do you regularly use?

27.1

**Comment by dgutov** [comment]
Would you switch to building Emacs from master (28.0.50) if this feature were only available that way?

**Comment by dgutov** [comment]
Never mind, seems like I'll have to implement wholly in this package anyway.

**Comment by dgutov** [comment]
See the new option `diff-hl-show-staged-changes`.

**Comment by dgutov** [comment]
And for more context, seems like Atom's extension behaves like diff-hl's current default, VS Code only diffs against the index, and Sublime has it configurable (like we do now): https://github.com/microsoft/vscode/issues/60389
