### ISSUE TITLE
[Feature request]  If point is not on a hunk, diff-hl-show-hunk will select the first hunk in current file instead.

### ISSUE THREAD

**Issue by zw963** [dgutov/diff-hl#169]
I often need find out where is the first hunk in current file, so, i have to do like this;

```cl
(defun show-first-hunk-on-current-buffer ()
  (interactive)
  (beginning-of-buffer)
  (diff-hl-show-hunk-next)
  )
(define-key diff-hl-command-map [(n)] 'show-first-hunk-on-current-buffer)
```

so, i thought maybe we can use `Ctrl-x v *` do same things, just if current point is not on a hunk.

Old behavior keep same anyway, but will more comfortable.

**Comment by yugaego** [comment]
I like this idea, though would probably oppose mapping `C-x v *` to act differently in vaguely similar situations.

How about adding the first hunk mapping to `C-x v <`?
(And maybe adding the last hunk mapping to `C-x v >` for symmetry.)

**Comment by zw963** [comment]
i consider we only need one command to display the (first/current) hunk in current buffer, anyway, after run this command, we can navigate on hunks use `n/p` hotkey.

**Comment by yugaego** [comment]
> after run this command, we can navigate on hunks use n/p hotkey.

But that would overwrite default mapping of `C-x v n` to `M-x diff-hl-revert-hunk`, wouldn't it?

Consider this alternative to re-map `n/p` in your own configuration:

```elisp
(with-eval-after-load 'diff-hl
  ;; `C-x v u` and  `C-x v r` are already mapped by `vc-mode`,
  ;; but we can rely on mnemonic `C-_` or `C-/` (both normally mapped to `M-x undo`).
  (define-key diff-hl-command-map (kbd "_") #'diff-hl-revert-hunk)

  ;; After the previous line change we can use `n/p` for navigation`.
  (define-key diff-hl-command-map (kbd "p") #'diff-hl-show-hunk-previous)
  (define-key diff-hl-command-map (kbd "n") #'diff-hl-show-hunk-next)

  ;; TOPIC of this thread, with the alternate function name.
  (define-key diff-hl-command-map (kbd "<") #'diff-hl-show-hunk-first))
```

Anyway, let's wait until @dgutov has some free time to look into this feature request and express his opinion whether
adding the suggested function `show-first-hunk-on-current-buffer` (aka potentially `diff-hl-show-hunk-first`)
would be a good idea overall.

**Comment by zw963** [comment]
> But that would overwrite default mapping of `C-x v n` to `M-x diff-hl-revert-hunk`, wouldn't it?

Oh, that just a personal select, it is not conflict with `diff-hl-revert-hunk`, because
after i pressing `C-x v n`, i get following interface.

![image](https://user-images.githubusercontent.com/549126/130435948-14284d27-f075-4e70-a164-545619ba4691.png)

I can use r to revert current hunk, n/p swith on hunks


>   (define-key diff-hl-command-map (kbd "<") #'diff-hl-show-hunk-first))

Yes, `<` hotkey is meaningful

**Comment by yugaego** [comment]
> not conflict with diff-hl-revert-hunk

Gotcha!

**Comment by dgutov** [comment]
I don't mind adding a couple of new commands, but when you are at the beginning of the buffer, you can just press `C-x v ]`, right?

Just making sure you're aware.

The show-hunk bindings should probably also use `[` and `]` instead of `n` and `p`, because `n` conflicts with `diff-hl-revert-hunk` anyway (`C-x v n`).

**Comment by dgutov** [comment]
Sorry, I only skimmed the thread: you already noted the conflict.

**Comment by zw963** [comment]
> I don't mind adding a couple of new commands, but when you are at the beginning of the buffer, you can just press `C-x v ]`, right?

What i means is,  if we can improve `C-x v *` to a more smart command, if current on hunk, it show hunk, if not, it will skip to beginning of buffer and then search first hunk, this will make use diff-hl more simple, we don't need remember to use `C-x v *` or `beginning of buffer then C-x v [`,  we need only one entry in the most of time,  that is `C-x v *`, will always find out the diff on current buffer if it exists.

`C-x v n` is not the point anyway. :smile:

**Comment by dgutov** [comment]
It already works like this:

* If on a hunk, show the hunk.
* Otherwise, scan backward in the buffer looking for a hunk (which fails when at the beginning of a buffer, obvious).

You are suggesting we add a third step:

* If the previous two fail, scan forward looking for a hunk.

I'm a little hesitant to do that because 1+2 makes the notion of the "current hunk" be either hunk at point or above it. And with 3, it will be less intuitively defined.

Note that if you install `smartrep` or, with the latest Emacs 28 snapshot, just enable `repeat-mode`, you can press `C-x v ] *` and see the "show hunk" action applied to the hunk below point.

**Comment by zw963** [comment]
> * If on a hunk, show the hunk.
> 
> * Otherwise, scan backward in the buffer looking for a hunk (which fails when at the beginning of a buffer, obvious).

sorry, Which command work like this way? 

 i don't consider scan backward is so useful anyway.

What i means is, searching a `exist on current buffer` hunk, this step useful when i want to show
what changes on current file before add changes into index.

sure, if point exactly on a hunk, show current hunk is reasonable anyway.

in fact, see diff of current buffer, i do it day and day, i finish this step use a external tools usually, e.g. beyond compare 4, but, anyway, i want to use emacs diff-hl instead, but i found, i have to do this

1. goto beginning of buffer,
2. search next hunk.

thank you.

**Comment by dgutov** [comment]
> sorry, Which command work like this way?

Both `diff-hl-revert-hunk` and `diff-hl-show-hunk`.

> i don't consider scan backward is so useful anyway

OK, let's try the fuzzier approach (looking in both directions) and see how it goes.

**Comment by zw963** [comment]
Sorry, i consider what changed was not fix this issue completely anyway, let me describe here for discuss anyway.

### bug.

When cursor on the beginning of buffer, and press `C-x v *`,  overlay appear  a flash, and skip to end of buffer immediately.
sorry can not create  a video for this because i use Wayland.

### Feature

1.   `diff-hl-show-hunk`(C-x v *)  it seem like try to find out the most closed hunk relative to current point, but for my point,  at least for me, i need a hotkey to traversing ALL hunks on current buffer, instead of guess the next hunk is above/under side?
if use C-x v *, i guess i have to use [ / ] several times to ensure exists which current buffer changes.

2.  n/p was removed unexpected anyway. i consider n/p is the most famous hotkey for down/up, so, we should keep it.
    use n as `git revert` is not so intuitive for me.

**Comment by zw963** [comment]
> Was there a hunk somewhere near the end of that buffer?

Near buffer end, but there is no diff, you can reproduce like this:

1. checkout diff-hl  repo from github.
2. git reset dbd46bf
3. use emacs open diff-hl-show-hunk.el
4.  goto beginning of buffer
5. C-x v *

I can reproduce this use [minimum](https://github.com/zw963/.emacs.d/blob/master/plugins/diff-hl/diff-hl_init.el) config with emacs 27.2

> That is a different feature request, right? Not what's in the title of this issue. You can open a new one.

Sorry, this is exact the purpose i open this issue, please check title, though, IMHO, bad english not describe so clear.

>  if use C-x v *, i guess i have to use [ / ] several times to ensure exists which current buffer changes.
> Sorry, I don't understand that sentence.

What i means is, assume i open a buffer, many changes was done on this buffer since last git commit.
assume my point on some place, i want to check this buffer all changes, how to do that?

 C-x v *,  assume it find out the next hunk after point, but, how to know if there exists changes before original
  point or after current point? so, what i have to do is, pressing `]` not key, until buffer end, then press `]` key
until beginning of buffer,  after all this done, i do my job for check `the hunks on this buffer`.

but this process is considered complicated, so , i propose a new command, which can always find hunks from beginning of buffer(that means, show current diff all hunks), or optional,  if current point on a hunk, it just find this hunk.(that means, show current hunk diff)

hope this time describe clear enough. 

> The problem is with the conflict with existing key bindings, as well as VC's bindings. I'll try to consider some other options.

I consider this `n` / `p` binding is only available if overlay is show, right?

![image](https://user-images.githubusercontent.com/549126/131519867-b1940e03-3157-4347-b35a-52e6fdcd2f62.png)

so, because overlay,  that is never conflict with other hotkey, right?

**Comment by dgutov** [comment]
> Near buffer end, but there is no diff, you can reproduce like this:

Hmm, I think I see the overlay flash and disappear, but point doesn't skip to the end of the buffer (it stays near the hunk where it should be).

So there is some problem with displaying the show-hunk overlay where the hunk was previously out of sight. I'll investigate that.

> What i means is, assume i open a buffer, many changes was done on this buffer since last git commit.
assume my point on some place, i want to check this buffer all changes, how to do that?

You would usually do that with `C-x v =`.

But if you really want to use the diff-hl UI only, how about: `M-< C-x v } } } } ...`? Or is that too many keypresses?

> i propose a new command, which can always find hunks from beginning of buffer(that means, show current diff all hunks)

I can add that too.

> or optional, if current point on a hunk, it just find this hunk.(that means, show current hunk diff)

Without this part, though: it doesn't make sense to me. "Show first hunk" should always mean "show first hunk". It's easy to see whether there is a hunk at point (in the margin), you can press `C-x v *` in that case.

> I consider this n / p binding is only available if overlay is show, right?

The main problem is with the `smartrep` or `repeat-mode` integration (there they do conflict). There can be other solutions to that.

The secondary problem is different keys depending on whether the overlay is shown or not. If you rarely use the "base" key bindings, it might be okay, but otherwise it can trip you up.

**Comment by zw963** [comment]
>  >  i propose a new command, which can always find hunks from beginning of buffer(that means, show current diff all hunks)

>  I can add that too.

Thank you, i find the most frequently operation i do is `show current buffer's all hunks`,  traversing on all hunks is always done for me several times to ensure not commit unexpected content into git. (though, i always do this use [beyond compare](https://www.scootersoftware.com/index.php) before.

> The secondary problem is different keys depending on whether the overlay is shown or not. If you rarely use the "base" key bindings, it might be okay, but otherwise it can trip you up.

for now, i always use diff-hl with overlay is show, anyway, i can binding it to n/p myself.

**Comment by yugaego** [comment]
> Thank you, i find the most frequently operation i do is show current buffer's all hunks, traversing on all hunks is always done for me several times to ensure not commit unexpected content into git

I'm seconding an approach of using
- `C-x v =` : the file(set) changes, bound to `M-x vc-diff`.
-  and `C-x v D` : all the tree files changes, bound to `M-x vc-root-diff`.

They *seem* to match the workflow that you describe, and adding them to `diff-hl-mode` *seems* to me would just duplicate built-in Emacs functionality.
Or maybe there're some benefits in potentially using exactly `diff-hl-mode` (instead of `vc-mode`) for showing all the hunks, that I'm missing?
[So far my imagination only showed me a benefit for a user who dislikes (or isn't aware of, or gives less preference to) `vc-mode` and bound to `diff-hl-mode` because of that.]

**Comment by zw963** [comment]
> Or maybe there're some benefits in potentially using exactly `diff-hl-mode` (instead of `vc-mode`) for showing all the hunks, that I'm missing?

I can always revert unexpected hunk if i  use diff-hl overlay feature.

**Comment by yugaego** [comment]
> I can always revert unexpected hunk if i use diff-hl overlay feature.

Hm, I've been falling back to the classical `git add -p` for the work with the patches on committing,
but now I've found there's `C-u C-c C-a` (`M-x diff-apply-hunk` with prefix argument) in `vc-diff` that reverses a hunk.
Though I'd probably expect it'd also auto-revert `vc-diff` buffer after reversing a hunk.

**Comment by zw963** [comment]
I propose please don't remove following keybinding anyway.

```diff
-    (define-key diff-hl-show-hunk--inline-popup-map (kbd "p") #'diff-hl-show-hunk-previous)
-    (define-key diff-hl-show-hunk--inline-popup-map (kbd "n") #'diff-hl-show-hunk-next)
```

i guess most of emacs user use n/p as next/previous,  in fact, i consider smartrep or repeat-mode not so useful AFAIK, and use new binding is awkful at least for me. :smile: 

----------------

And for clarify purpose, i guess if my bad english lead this discuss in a differnt direction, as least for the purpose my original issue purpose.

so, let us read code, following code is all i want to do.

```cl
(defun diff-hl-show-hunk-or-show-first-hunk ()
  (interactive)
  (if (diff-hl-hunk-overlay-at (point))
      (diff-hl-show-hunk)
    (progn
      (beginning-of-buffer)
      (diff-hl-show-hunk-next))
    ))

(define-key diff-hl-command-map [(*)] 'diff-hl-show-hunk-or-show-first-hunk)
(define-key diff-hl-show-hunk--inline-popup-map (kbd "p") #'diff-hl-show-hunk-previous)
(define-key diff-hl-show-hunk--inline-popup-map (kbd "n") #'diff-hl-show-hunk-next)
(define-key diff-hl-show-hunk--inline-popup-map (kbd "r") #'diff-hl-show-hunk-revert-hunk)
```

**Comment by dgutov** [comment]
> I propose please don't remove following keybinding anyway

OK, I have reverted that commit. Will have to find another solution for the smartrep/repeat-mode problem.

> so, let us read code, following code is all i want to do

I see the code, and the logic doesn't make much sense to me, sorry. Why would it jump to the first hunk, if there is a hunk above it, for example? Or a hunk both above and below point.

I can add a command which will always bring you to the first hunk, however.

**Comment by dgutov** [comment]
BTW, can you still reproduce the problem from https://github.com/dgutov/diff-hl/issues/169#issuecomment-909289157?

**Comment by dgutov** [comment]
And yup:

> but now I've found there's C-u C-c C-a (M-x diff-apply-hunk with prefix argument) in vc-diff that reverses a hunk

This is also what I do on a regular basis.

One day we'll be able to commit individual hunks from VC, but not yet.

**Comment by zw963** [comment]
> BTW, can you still reproduce the problem from

I can't, It seem like get fixed now



> I see the code, and the logic doesn't make much sense to me, sorry.

Okay, that fine, as you see, i write myself function to do this.

> Why would it jump to the first hunk, if there is a hunk above it, for example? Or a hunk both above and below point.

If fine to not add this function anyway, but for the reason, i would want see ALL HUNKS for current buffer before i add to git index,
so, the meaningful way to do this is: `from top to buttom`, or `from buttom to top`,  individually, i select former, in fact, i can use latter too, but it not conveniently if on the buffer middle,  because you don't know fi exists how many hunks after/before  current point.

>  but now I've found there's C-u C-c C-a (M-x diff-apply-hunk with prefix argument) in vc-diff that reverses a hunk

In fact, i never do like this, i will try it next time.

**Comment by zw963** [comment]
@dgutov , i can reproduce the problem from #169 (comment) again ...

the wierd things is: when this happen, and when i want to jump to beginning of buffer use `M-<`,  it not work correct, it jump to middle of buffer (for my case, line 73),  i guess this line is the `first hunk's last line` for current buffer. i have to double `M-<` again to beginning of buffer.

**Comment by dgutov** [comment]
@zw963 Reproducing it seems to be the difficult part for now.

Can do you it consistently? Is scenario from https://github.com/dgutov/diff-hl/issues/169#issuecomment-909289157 still the easiest way to do it?

> when this happen, and when i want to jump to beginning of buffer use M-<, it not work correct, it jump to middle of buffer (for my case, line 73), i guess this line is the first hunk's last line for current buffer. i have to double M-< again to beginning of buffer

This part I can reproduce, because it also happens when the hunk's inline-popup is displayed properly. Not sure about the exact mechanism yet.

**Comment by zw963** [comment]
> Can do you it consistently?

I remember not always. maybe wrong.


> Is scenario from [#169 (comment)](https://github.com/dgutov/diff-hl/issues/169#issuecomment-909289157) still the easiest way to do it?

Yes.

**Comment by dgutov** [comment]
I have hopefully fixed this one.

Not ideally (a minor feature was lost). Perhaps  @alvarogonzalezsotillo could propose a better fix sometime later.

**Comment by zw963** [comment]
> I have hopefully fixed this one.
> 
> Not ideally (a minor feature was lost). Perhaps @alvarogonzalezsotillo could propose a better fix sometime later.

It seem like fixed now. thank you.

**Comment by dgutov** [comment]
Thanks for checking.

Are you otherwise content with how things work, or do we need a command like `diff-hl-first-hunk`?

**Comment by dgutov** [comment]
Thanks.

It seems specific to your particular workflow, so let's keep it in your init script.

**Comment by alvarogonzalezsotillo** [comment]
> I have hopefully fixed this one.
> 
> Not ideally (a minor feature was lost). Perhaps @alvarogonzalezsotillo could propose a better fix sometime later.

`diff-hl-inline-popup--ensure-enough-lines` had the "smell" of fragile GUI code: some forced `redisplay`s and some `execute-later`s .

Also, It tries to solve a corner case, so I think removing it is a good fix.

**Comment by dgutov** [comment]
(And that's issue #71)
