### ISSUE TITLE
when do revert for current hunk, only show the (will be reverted) diff of current hunk. (or, even disable show diff, revert immediately)

### ISSUE THREAD

**Issue by zw963** [dgutov/diff-hl#173]
![image](https://user-images.githubusercontent.com/549126/138583188-614a6637-4149-4579-9041-7239aef15720.png)

As above screenshot, i only want revert the current hunk, that is, the font settings line.
but, when i press `r` key to try to revert this line code, right side, it give me many diff not only current hunk, which not so useful for me, and more bad, it give me a misconception, i will revert all diff show in right side.

i don't know emacs VC if exists function for `diff of current hunk`, but, i consider if not,  we can add a defcustom, which can let user disable show this diff buffer, and revert it directly instead.

  because, anyway, we can see the major changes directly on left side as following, diff buffer not so useful. 

![image](https://user-images.githubusercontent.com/549126/138583447-ff248ac3-2241-4eb6-a0eb-585f7a85def5.png)

**Comment by dgutov** [comment]
> fancy-narrow only 400 LOC, include comments and black. : )

There are other reasons not to inline it: the users might have already customized its "blocked" face (or themes did). We'd miss out on some bugfixes too, I guess.

**Comment by dgutov** [comment]
@yugaego Thanks for the diff, see below how both options look in my session.

fancy-narrow:

![Screenshot from 2021-11-01 03-40-09](https://user-images.githubusercontent.com/271877/139607293-af6ce1ca-4434-43e8-b8d9-53d91da4c0c5.png)

emphazie-hunk:

![Screenshot from 2021-11-01 03-42-25](https://user-images.githubusercontent.com/271877/139607358-ffa1dd19-58fd-4f84-808f-d98245928eca.png)

Fancy-narrow probably does a better job hiding the other hunk (which just added two empty lines), but both seem a little... untidy? I don't know. Happy to have either as an option, though.

Let's consider some more options. First, a simple narrowing to the hunk but with context added (we know how to do that now). It would look like this:

![Screenshot from 2021-11-01 03-47-29](https://user-images.githubusercontent.com/271877/139607644-2bb85dbd-b60d-4811-8a42-ef215a0af234.png)

It still looks a little "barren" with smaller hunks, though:

![Screenshot from 2021-11-01 03-50-04](https://user-images.githubusercontent.com/271877/139607682-16730691-13d9-4430-929e-16ec72dbfb8e.png)

**Comment by dgutov** [comment]
And going back to the current default behavior, IMHO it might be primarily problematic with dark-background themes, where the first column doesn't stand out as obviously. Because this looks pretty obvious to me:

![Screenshot from 2021-11-01 03-53-33](https://user-images.githubusercontent.com/271877/139607822-3b560a31-6c55-40f7-aeb3-539fe89f2a85.png)

Obviously I'm biased. But perhaps someone would like to propose a different definition for the `diff-hl-reverted-hunk-highlight` face, which would make it stand out on dark-bg themes more?

I've also considered decorating the hunk boundaries, but the `:box` attribute is not very flexible, and it won't work when the hunk is the last in the buffer. It doesn't look particularly good:

![Screenshot from 2021-11-01 04-19-27](https://user-images.githubusercontent.com/271877/139608909-9e4a355e-98eb-4483-ab58-0fa00ce5243f.png)

Or instead of the first column we could use the fringe (or the margin) to indicate the lines which will be used. Though I'm not sure which graphic/color to use (or chars, for the margin).

**Comment by yugaego** [comment]
Hi Dmitry,

> a simple narrowing to the hunk but with context added (we know how to do that now)

I suspect that's what many (maybe most) of the users would expect to see.

A similar approach was discussed before:

> > Maybe the suggested narrow-to-region solution (perhaps showing a bit wider area) could replace the current default?

> That can work, though I was kind of worried to show only one hunk (which often might contain only a few lines) without any context. The rest of the window being empty, it seems like a waste of screen space.

If that's still a worry, my preference would go to the "fancy-narrow" like output.
("emphasize-hunk" indeed was bad at un-fontifying the other hunks.)
If this approach is chosen, I could probably extract the basic parts from the fancy-narrow, so that avoid non-maintained third-party package dependency. I assume it could result in something similar to "emphasize-hunk" in the code structure , but with one more definition added (close to `fancy-narrow-properties`) and `diff-hl-revert-emphasize-hunk` improved (extracted from `fancy-narrow-to-region` + `fancy-narrow--propertize-region`).
 
> going back to the current default behavior, IMHO it might be primarily problematic with dark-background themes, where the first column doesn't stand out as obviously. 

Yeah, might be. Your light-bg screenshot show better visibility than on my dark-bg setup.

> But perhaps someone would like to propose a different definition for the diff-hl-reverted-hunk-highlight face, which would make it stand out on dark-bg themes more?

I had considered a couple of options but wasn't fascinated with the results.

> but the :box attribute is not very flexible, and it won't work when the hunk is the last in the buffer. It doesn't look particularly good

Yeah. It doesn't look like a good tool to signify a hunk. 

> instead of the first column we could use the fringe (or the margin) to indicate the lines which will be used.

I'm afraid fringes would suffer again from the insufficient visibility.

**Comment by dgutov** [comment]
Hi Yuzhana,

> A similar approach was discussed before:

Yup. It might be better with the added context. Let's try it.

> If this approach is chosen, I could probably extract the basic parts from the fancy-narrow, so that avoid non-maintained third-party package dependency. I assume it could result in something similar to "emphasize-hunk" in the code structure , but with one more definition added (close to fancy-narrow-properties) and diff-hl-revert-emphasize-hunk improved (extracted from fancy-narrow-to-region + fancy-narrow--propertize-region).

I just noticed that it's annotated as "unsupported". If you or someone else prefer this approach, I'm happy to review such PR, but as for the default behavior, one of the other options seems better so far (either narrow-to-region or the current default :shrug:).

It could be decided by a vote, though, sometime later. Someone could open a poll on reddit.

**Comment by yugaego** [comment]
> Yup. It might be better with the added context. Let's try it.

Looks great to me. 👍🏻

**Comment by zw963** [comment]
When i try to do revert use C-x v n, or pressing `r` from show hunk UI, always get failing message:

diff-beginning-of-hunk: Can’t find the beginning of the hunk.

so,  if you meet same issue as me?

**Comment by dgutov** [comment]
@zw963 I can repro.

Will need to add explicit support for `diff-hl-show-staged-changes`=`nil` to `diff-hl-revert-hunk`.

**Comment by dgutov** [comment]
That happens when you have some staged changes, right?

**Comment by zw963** [comment]
> Will need to add explicit support for `diff-hl-show-staged-changes`=`nil` to `diff-hl-revert-hunk`.

Yes, i done it.



> That happens when you have some staged changes, right?

No, it can reproduce use my (many) config on some cases (no stage)

but,  after use only diff-hl.el test it again,  i can't reproduce it now, so, i consider another package broken this.

after check it, this issue caused by following code in my own config, when fancy-narrow is required, revert failed.

```cl
(defun diff-hl-revert-narrow-to-hunk (end)
  (if (fboundp 'fancy-narrow-to-region)
      (fancy-narrow-to-region (point) end)
    (narrow-to-region (point) end)))

(setq diff-hl-highlight-revert-hunk-function #'diff-hl-revert-narrow-to-hunk)
```

After move above code, revert start to working now.

thank you.

**Comment by dgutov** [comment]
Oh, that's a different bug. :-(

**Comment by dgutov** [comment]
I'm not sure what exactly, but something in fancy-narrow breaks `diff-find-file-name`, stopping it from reading the needed header. Maybe it's the `intangible` property or whatever, but it's not supposed anymore (`inhibit-point-motion-hooks` defaults to t these days). Debugging didn't help much, and the Commentary in `fancy-narrow` doesn't recommend to use it in Lisp programs anyway, so... anybody who really wants to use it, is welcome to help figuring this out.

**Comment by dgutov** [comment]
> Will need to add explicit support for diff-hl-show-staged-changes=nil to diff-hl-revert-hunk.

This is now done, BTW. With this setting, `diff-hl-revert-hunk` now works with changes against the staging area.

**Comment by zw963** [comment]
> Will need to add explicit support for `diff-hl-show-staged-changes`=`nil` to `diff-hl-revert-hunk`.

In fact, i am not ensure what this support means, 

anyway, i guess your means is,  when set `diff-hl-show-staged-changes`=`nil`(yes, i set it),  and i test on newest master(6fa3af0), i can revert code sccessful now with `C-x v n` Or press `r` from show hunk UI.

**Comment by zw963** [comment]
> When i try to do revert use C-x v n, or pressing `r` from show hunk UI, always get failing message:
> 
> diff-beginning-of-hunk: Can’t find the beginning of the hunk.
> 
> so, if you meet same issue as me?

Just for report.
And, for this issue. (when use with fancy-narrow), i get following error message instead original.

ad-Advice-buffer-substring: Args out of range: #<killed buffer>, 935, 937

And it seem like introduce a new issue on master, i will report on #117

**Comment by dgutov** [comment]
> In fact, i am not ensure what this support means,

It means that the "revert" command works against the staged area as well. I.e. when some version of the current file is staged, the changes you can revert will be computed against this staged version.

> anyway, i guess your means is, when set diff-hl-show-staged-changes=nil(yes, i set it), and i test on newest master(6fa3af0), i can revert code sccessful now with C-x v n Or press r from show hunk UI.

The previous mismatch in the face of staged changes could indeed bring errors and surprising behavior.

> And, for this issue. (when use with fancy-narrow), i get following error message instead original.

I had to give up on investigating the fancy-narrow integration. But patches welcome.

> And it seem like introduce a new issue on master

Were you going to file a new issue?

**Comment by zw963** [comment]
> the changes you can revert will be computed against this staged version.

So, what you means `revert` here for staged version, is `git reset` on command line, right?


> Were you going to file a new issue?

Sorry, i mean #177 , you saw it.
