### ISSUE TITLE
compiler error with latest master

### ISSUE THREAD

**Issue by ouboub** [dgutov/diff-hl#174]
I pulled the latest master, however when running make 
(using emacs master emacs-repository-version
"83a915d3dfafd5f3d737afe1e13b75e4dd3aef96" that is 6 month old I obtain
quite some errors and failures that I attach.
[error.txt](https://github.com/dgutov/diff-hl/files/7454818/error.txt)

**Comment by dgutov** [comment]
Hi!

Seems like you have launched the tests from the package installation directory, instead of 'git clone'-ing the repository first.

The tests, as written, depend on there being a Git repository "outside", so it's not a problem if they fail in a non-version-controlled directory.

Let me know if got it wrong, though. And thanks anyway.

**Comment by ouboub** [comment]
Hm, 
I recloned the repository
step to reproduce the behaviour:
  - git clone https://github.com/dgutov/diff-hl.git
  - edit make file:
    change EMACS ?= emacs
    to
    EMACS ?= /opt/emacs28/bin/emacs
  - run make

  the same error pops up

  out of curiosity: 

  - what is ?=
  - and +=
    supposed to do?

**Comment by dgutov** [comment]
> git clone https://github.com/dgutov/diff-hl.git

Then `cd diff-hl`, right?

**Comment by ouboub** [comment]
> > git clone https://github.com/dgutov/diff-hl.git
> 
> Then `cd diff-hl`, right?

yes of course I did this! you can be ensured, otherwise there would be no make file run run 
and make would return
```tex/vorlesungen/Quiros-Aufzeichnungen/```
or are you saying diff-hl contains another diff-hl directory?
if it does, I could not clone it

**Comment by ouboub** [comment]
I tried it again:
make clean
make
now it works, hmmmm? not sure what to think, I guess close the bug

**Comment by dgutov** [comment]
I guess `make clean` is what did it. I guess the Makefile is not well-written enough to recompile files as they change.

Thanks for being thorough.
