### ISSUE TITLE
Same hotkey binding to both next/revert when navigating use diff-hl-show-hunk

### ISSUE THREAD

**Issue by zw963** [dgutov/diff-hl#177]
Following is a reproduce:

1.  open diff-hl.el file, and goto beginning-of-buffer

2. running `diff-hl-show-hunk`, get UI like this

![image](https://user-images.githubusercontent.com/549126/140641206-50483e04-ba44-44aa-9763-f6adac3ed651.png)

3.  then, i want to pressing `n` to goto next hunk, get following ui to try to revert current hunk

![image](https://user-images.githubusercontent.com/549126/140641246-2ec84af8-9f6d-497b-b84e-7e119b6e1cb1.png)

**Comment by dgutov** [comment]
Yeah, the problem of mismatching key bindings is most apparent when `smartrep` or `repeat-mode` are used.

I suppose the solution can be in writing the integrations in a more manual way (lines 852 to 872 in `diff-hl.el`). I'll try to get around to this this week, but patches welcome.

**Comment by zw963** [comment]
> Yeah, the problem of mismatching key bindings is most apparent when `smartrep` or `repeat-mode` are used.

Yes, when i try to reproduce this issue, i enable repeat-mode, after i disable it, it work as expected now.

**Comment by dgutov** [comment]
Should be fixed now. `repeat-mode` won't touch the "show hunk" commands, which have their own persistent UI already.

**Comment by zw963** [comment]
> Should be fixed now. `repeat-mode` won't touch the "show hunk" commands, which have their own persistent UI already.

Yes, i test it, it works now.
