### ISSUE TITLE
Startup dependency issue

### ISSUE THREAD

**Issue by Ergus** [dgutov/diff-hl#181]
Hi:

I installed from elpa and I am getting this error: `(void-function smartrep-define-key)` 

It seems like `smartrep` is not declared as a dependency for melpa. I think that with the new `repeat-mode` this may be unneeded, because the package seems to be also unmaintained (last commit was in 2015)... but probably you want to keep it compatible with the old emacs versions, so any solution you choose (remove the dependency code or add the package as a dependency) may be fine IMO

**Comment by dgutov** [comment]
Hi!

The only call to `smartrep-define-key` happens inside a block predicated on `(when (require 'smartrep nil t) ...)`.

Any idea why it happens on your machine? Is it possible that you have `smartrep` actually installed, but some incomplete version of it?

**Comment by Ergus** [comment]
Another package was adding an advise to my require function... now solved
