### ISSUE TITLE
Fringe indicator disappears when editing until buffer is saved, and `diff-hl-flydiff-mode` does not seem to work on Windows

### ISSUE THREAD

**Issue by jjnilton** [dgutov/diff-hl#183]
When editing, the related fringe indicator disappears, and only reappears when saving the buffer. And enabling `diff-hl-flydiff-mode` makes the indicators disappear.

I'm using Emacs 27.2 (Windows 10):

Here's an example, I'm saving manually with C-x C-s:
![emacs-diff-hl](https://user-images.githubusercontent.com/228200/159128216-ee7f29b3-b120-4f4f-9148-a9eba18642af.gif)

I could reproduce the issue with `emacs -Q -l diff-hl.el`.

Is there any workaround to make it work as in Linux where the fringe indicator reappears without having to save, even without `diff-hl-flydiff-mode`?

**Comment by ouboub** [comment]
>>> "J" == JJ  ***@***.***> writes:

> When editing, the related fringe indicator disappears, and only
> reappears when saving the buffer. And enabling `diff-hl-flydiff-mode`
> makes the indicators disappear.

> I'm using Emacs 27.2 (Windows 10):

> ![emacs-diff-hl](https://user-images.githubusercontent.com/228200/159128216-ee7f29b3-b120-4f4f-9148-a9eba18642af.gif)

Sorry to come off with an off topic question, but how did you generate
this gif file? That seems very handy for bug reports and the alike.

Thanks

Uwe Brauer

**Comment by jjnilton** [comment]
> Sorry to come off with an off topic question, but how did you generate this gif file? That seems very handy for bug reports and the alike.

I used a program called [ScreenToGif](https://github.com/NickeManarin/ScreenToGif).

**Comment by dgutov** [comment]
The disappearing of fringer indicators in the default config is by design: to show that the information is outdated.

But what about flydiff not working in Windows? Have you tried downloading a port of `diff` and putting it somewhere in PATH?

**Comment by dgutov** [comment]
Speaking of undoing that default behavior, though, I suppose you could call the reverse of `(add-hook 'after-save-hook 'diff-hl-update nil t)` in `diff-hl-mode-hook`.

**Comment by dgutov** [comment]
You'll get outdated info on screen this way, though.

**Comment by jjnilton** [comment]
> The disappearing of fringer indicators in the default config is by design: to show that the information is outdated.

I see it now. I think what was confusing me was if started emacs with ` '(diff-hl-flydiff-mode t)` in my .emacs, and then disabled `diff-hl-flydiff-mode`, I got this behavior:
- The fringe indicators changing to outdated info without saving.
- The fringe indicators change to updated info when saving.

Example:
![emacs-diff-hl-behav](https://user-images.githubusercontent.com/228200/159141179-b00c8d79-ef2f-4325-b1ad-df5346737ae6.gif)

I could not reproduce consistently, though.

> But what about flydiff not working in Windows? Have you tried downloading a port of diff and putting it somewhere in PATH?

Tried and it worked! Thanks! Though, the Windows version of diff is ancient (2.8.7), and I haven't found an alternative yet. Maybe using the diff on WSL would work, but couldn't get it working yet.

For example, instead of using `diff`, it would use `wsl -e diff`.

> Speaking of undoing that default behavior, though, I suppose you could call the reverse of (add-hook 'after-save-hook 'diff-hl-update nil t) in diff-hl-mode-hook. You'll get outdated info on screen this way, though.

Not sure how I could that on my config, but since flydiff works now and the behavior I was seeing was erroneous, I think I'll keep the defaults.

**Comment by ouboub** [comment]
>>> "J" == JJ  ***@***.***> writes:

>> Sorry to come off with an off topic question, but how did you generate this gif file? That seems very handy for bug reports and the alike.
> I used a program called [ScreenToGif](https://github.com/NickeManarin/ScreenToGif).

Thanks, that is windows only it seems.

**Comment by dgutov** [comment]
> I could not reproduce consistently, though.

If you have can write a step-by-step reproduction scenario, that would help.

> Though, the Windows version of diff is ancient (2.8.7)

Is that a problem? Is it slow or etc?

> For example, instead of using diff, it would use wsl -e diff.

You could be able to do that by writing a shell script that calls wsl. Simply setting `diff-command` to that string is unlikely to work since it expects the name of a program (because it's used with `call-process`).

**Comment by jjnilton** [comment]
> If you have can write a step-by-step reproduction scenario, that would help.

Unfortunately, I wasn't able to reproduce it again. If I manage to reproduce it again I'll share here.

> Is that a problem? Is it slow or etc?

I didn't notice anything wrong, but I read there's at least one bug related to PDF files, and since there were quite a few updates after 2.8.7 (released in 2004), there's possibly more.

> You could be able to do that by writing a shell script that calls wsl. Simply setting diff-command to that string is unlikely to work since it expects the name of a program (because it's used with call-process).

I'll try that, if I manage to make it work I'll share it here.

Thanks for all your help and explanation, and for sharing this great package.

**Comment by jjnilton** [comment]
I tried to make a .bat script to "forward" wsl diff, but it did not work in emacs, but I noticed that git comes with a diff binary located at `C:\Program Files\Git\usr\bin\diff.exe`, so placing it (and the required .dll) on the path worked.

**Comment by JordanAnthonyKing** [comment]
> I noticed that git comes with a diff binary located at `C:\Program Files\Git\usr\bin\diff.exe`, so placing it (and the required .dll) on the path worked.

I've run into the same issue as you, I have the appropriate folder in my path and can run diff from the command line, but it's not working from within emacs. What do you mean by 'the required .dll?'
