### ISSUE TITLE
question: diff-hl-margin-local-mode

### ISSUE THREAD

**Issue by liuyinz** [dgutov/diff-hl#194]
https://github.com/dgutov/diff-hl/blob/68fb280b300c5d8460cc7b9183e29fb3ec604136/diff-hl-margin.el#L109-L119

Why not restore `width-var` to origin value like `diff-hl-highlght-function` when disable `diff-hl-margin-local-mode` ?
Maybe `width-var` is not equal to 0 by user default settings.

**Comment by dgutov** [comment]
Fair question. Let's store the previous value.
