### ISSUE TITLE
Feature request: provide more flexibility to set additional settings in vc-git-diff-switches

### ISSUE THREAD

**Issue by lhernanz** [dgutov/diff-hl#198]
The current code (in the `diff-hl-with-diff-switches` macro) ignores most of the values of the variable `vc-git-diff-switches` (it just preserves the diff algorithm). Although I can understand that this might be needed to provide a more predictable output, it has the problem that you cannot set the `textconv` setting. This setting is needed in order to make `vc-mode` to work with [git crypt](https://github.com/AGWA/git-crypt) that uses filters to encrypt/decrypt the files. 

It would be amazing if you would add `textconv` to the list of allowed settings or if you could provide a more flexible mechanism to specify additional git settings.

In any case, thank you very much for creating this package!

**Comment by dgutov** [comment]
I haven't tried git-crypt yet, but according to the manual

    textconv filters are enabled by default only for [git-diff](https://git-scm.com/docs/git-diff)

...probably meaning that `--textconv` is already enabled for `git diff` by default (and whether it is applied is determined by `.gitattributes`). So does adding the above setting do anything?

**Comment by lhernanz** [comment]
Yes, this patch works. It is what I am using now.

You are right that the diff operation is already doing the conversion but
the diff-index operation, that is the one that is being used by Emacs,
needs the setting to be specified in the command line. I have been unable
to find any setting in .gitattributes to enable it.

Thanks
Regards

**Comment by dgutov** [comment]
Ah right, makes sense, thanks.
