### ISSUE TITLE
fringe indicators don't work when emacs is started in --daemon mode

### ISSUE THREAD

**Issue by steckerhalter** [dgutov/diff-hl#2]
i'm always using the emacsclient to get my GTK emacs frame.

``` lisp
(when (window-system)
  (define-fringe-bitmap 'diff-hl-bmp-empty [0] 1 1 'center)
  (diff-hl-define-bitmaps))
```

the window-system isn't available yet when the daemon starts. it should check for that when the frame is created and not when the mode is loaded

is it supposed to work without the GUI?

I really like this mode... it's kinda great to see the what changed and to be able to revert single hunks like that

**Comment by manuel-uberti** [comment]
I am using latest version of ```diff-hl```. I have ```(global-diff-hl-mode)``` in my init.

When starting Emacs in daemon mode, there are indicators on the fringe. If call ```(global-diff-hl-mode)``` twice (first disabling it, then enabling it back again), indicators appear.
