### ISSUE TITLE
diff-hl-dired-mode inside docker 

### ISSUE THREAD

**Issue by nehrbash** [dgutov/diff-hl#204]
I have not looked into this too deeply yet but diff-hl-dired-mode is falsely  reporting changes when no changes have been made inside a docker workspace. That is to say, every single file is being reported as changed.

**Comment by dgutov** [comment]
Any chance this could be related to different environments between host and container? Something related to line endings?

Do you see this all the time? With every project that you tried?

**Comment by dgutov** [comment]
Seems to work okay here.

At least if you use the built-in `docker` Tramp method in Emacs 29.
