### ISSUE TITLE
Usage of /dev/shm for temporary files not supported on FreeBSD

### ISSUE THREAD

**Issue by procrastinat0r** [dgutov/diff-hl#219]
Hi,

using diff-hl in Doom Emacs on FreeBSD 13.2 causes error messages like

`Error running timer ‘diff-hl-flydiff-update’: (file-error "Creating file with prefix" "Operation not supported" "/dev/shm/buffer-content-")
`

Reason is `diff-hl-diff-buffer-with-reference` switches `temporary-file-directory` to "/dev/shm" if /dev/shm exists as directory. On FreeBSD this directory exists but does not have the same usage as in Linux (see https://news.ycombinator.com/item?id=37277369 and https://superuser.com/questions/45342/when-should-i-use-dev-shm-and-when-should-i-use-tmp).

Fixed it for me by changing

```
modified   diff-hl.el
@@ -1098,7 +1098,7 @@ CONTEXT-LINES is the size of the unified diff context, defaults to 0."
     (let* ((dest-buffer (or dest-buffer "*diff-hl-diff-buffer-with-reference*"))
            (backend (or backend (vc-backend file)))
            (temporary-file-directory
-            (if (file-directory-p "/dev/shm/")
+            (if (and (not (eq system-type 'berkeley-unix)) (file-directory-p "/dev/shm/"))
                 "/dev/shm/"
               temporary-file-directory))
            (rev

```

**Comment by dgutov** [comment]
Hi!

Thanks for the report. I've made the use of it specific to GNU/Linux systems.

**Comment by procrastinat0r** [comment]
Hi, thanks for fast response!
