### ISSUE TITLE
Temporary file names with colons are not allowed on Windows operating system

### ISSUE THREAD

**Issue by bartelmarkus** [dgutov/diff-hl#222]
Unfortunately, in connection with Git, the plugin does not readily work on Windows due to the choice of this one `:` character as a separator in the temporary file names:
https://github.com/dgutov/diff-hl/blob/f66345ed1f174e844ce43d8225613b7b0fc3e253/diff-hl.el#L1147-L1150

If this function is modified or advised to use i. e. percentage characters, the plugin works as intended.

My workaround advice that I put in my config around `diff-hl-make-temp-file-name` looks as follows (ot replaces the colon in question with a percentage sign):

```emacs lisp
(defun remove-colon-in-file-name (fname)
  (replace-regexp-in-string ":\\([^:]+\\)$" "%\\1" fname))

(with-eval-after-load 'diff-hl
  (advice-add 'diff-hl-make-temp-file-name :filter-return #'remove-colon-in-file-name))
```

Would this be an easy fix where just another windows compatible character needs to be chosen or are there other problems (maybe file naming conflicts) that arise from using i. e. an underscore or percent sign?

**Comment by dgutov** [comment]
Hi! Does this work for you?

```diff
diff --git a/diff-hl.el b/diff-hl.el
index 0afa9d4..c9b5c11 100644
--- a/diff-hl.el
+++ b/diff-hl.el
@@ -1146,7 +1146,7 @@ CONTEXT-LINES is the size of the unified diff context, defaults to 0."
 
 (defun diff-hl-git-index-revision (file object-name)
   (let ((filename (diff-hl-make-temp-file-name file
-                                               (concat ":" object-name)
+                                               (concat ";" object-name)
                                                'manual))
         (filebuf (get-file-buffer file)))
     (unless (file-exists-p filename)
```

**Comment by bartelmarkus** [comment]
Hi Dmitry,
This works just fine. Thank you so much!

**Comment by dgutov** [comment]
Pushed the change, thanks for testing. :+1:
