### ISSUE TITLE
Wrong highlight when using `diff-hl-reference-revision` with dynamic revision like "HEAD^"

### ISSUE THREAD

**Issue by whhone** [dgutov/diff-hl#224]
**Repro steps**
1. `(setq diff-hl-reference-revision "HEAD^")`
2. Enable flydiff mode `(diff-hl-flydiff-mode +1)`
3. Make some commits. (`HEAD^` is now a different revision)

**Expected**
diff-hl can give diff results with the new `HEAD^`.

**Actual**
diff-hl gives stale diff results.

**Causes**
The temp files in `/dev/shm/` are not updated or deleted. e.g., `/dev/shm/path!to!file.~HEAD^~`

**Comment by dgutov** [comment]
Hi! Thanks for the report.

That should fix it, please verify.

**Comment by whhone** [comment]
It fixes git but not hg, which is what I also use :-)

```
(defun my/diff-hl-clear-temp-files ()
  "Clear the diff-hl fig temp files."
  (interactive)
  (let ((temporary-file-directory "/dev/shm/"))
    (dolist (file (directory-files temporary-file-directory))
      (when (string-match "myrev" file)
        (delete-file (concat temporary-file-directory file))))))
````

**Comment by whhone** [comment]
I am not sure if there is a elisp function from vc-hg but this hg command can show the underlying revision of "myrev": `hg identify -r <myrev> -i`. We can probably use it.

**Comment by dgutov** [comment]
Thanks! Added a clause for Hg using `hg identify`.

**Comment by whhone** [comment]
Thanks!
