### ISSUE TITLE
Highlight diffs on-the-fly

### ISSUE THREAD

**Issue by PythonNut** [dgutov/diff-hl#33]
The README indicates that showing accurate diffs even if the buffer has been modified, but not saved is a possible feature. This is an issue to track the discussion and development of this feature, if this is deemed worthwhile to implement.

**Comment by PythonNut** [comment]
How do we intend to fix it? I've never encountered this before. Obviously, we do want it to work in current versions. Do we advise it conditionally on the version?

**Comment by dgutov** [comment]
> Obviously, we do want it to work in current versions

Only if it's not too much trouble. Emacs releases come and go. Not everyone has to have access to the latest goodies. :)

> Do we advise it conditionally on the version?

Probably. First we'll have to fix it in the core, and the advice could be based on that fix.

**Comment by PythonNut** [comment]
For `git`:

```emacs
(defadvice vc-git-working-revision
  (around (file) activate preactivate compile)
  "Git-specific version of `vc-working-revision'."
  (vc-git--rev-parse "HEAD"))
```

I haven't used the other `vc` systems to the point where I can intelligently comprehend their code, and checking them all seems to be a daunting task.

**Comment by dgutov** [comment]
Yes, the above should work. But doing just this will make VC show `Git-ffafafafafaf` in the mode-line where it now shows `Git-master`, which would be a step back in functionality.

Maybe the `working-revision` VC command needs a new optional "literal" argument.

**Comment by PythonNut** [comment]
Hm... I suppose the question is what we mean by _revision_. In my mind, a revision must be immutable. `master` is not a revision, but `ffafafafafaf` is. `master` is a branch.

It's probably a little late to fix this without breaking tons of stuff. 

> Maybe the `working-revision` VC command needs a new optional "literal" argument.

That would require us to update all of the backends, right? That would require quite a few people (unless we know anyone who knows a ton of vc systems).

**Comment by dgutov** [comment]
> I suppose the question is what we mean by revision... It's probably a little late to fix this without breaking tons of stuff.

Yes, now what VC means by "revision" is defined by the places it's used in.

> That would require us to update all of the backends, right? That would require quite a few people (unless we know someone who knows a ton of vc systems).

Not if the argument is optional, then the backends can be updated gradually. And the backends that alreay return a "concrete" revision would be unaffected.

**Comment by PythonNut** [comment]
Handling this is a half step more delicate than I planned because `vc` _also_ caches the revisions in memory.

**Comment by dgutov** [comment]
> vc also caches the revisions as lisp attributes

Where? I can't see that in `vc-git-find-revision` or `vc-find-revision`.

> Also, it struck me that this will cost one more disk access per diff (for the index).

At what point?

**Comment by PythonNut** [comment]
* See this code:
```emacs
(defun vc-working-revision (file &optional backend)
  "Return the repository version from which FILE was checked out.
If FILE is not registered, this function always returns nil."
  (or (vc-file-getprop file 'vc-working-revision)
      (progn
	(setq backend (or backend (vc-responsible-backend file)))
	(when backend
	  (vc-file-setprop file 'vc-working-revision
			   (vc-call-backend backend 'working-revision file))))))
```

* Every time we diff, we need to check if the current cached file from `HEAD` is out-of-date. This costs us one `rev-parse` in git's case.

**Comment by dgutov** [comment]
Oh, right. I was looking at wrong functions.

> Every time we diff, we need to check if the current cached file from HEAD is out-of-date.

When does that happen? Emacs does not cache the `git diff` output, so maybe passing `HEAD` verbatim into various commands should work just as well.

By the way, you should feel free to bring up various problems either at emacs-devel, or via `M-x report-emacs-bug`.

> I just noticed that the indentation in vc is a horrible mess of both tabs and spaces

Let's not go there. :)

**Comment by PythonNut** [comment]
> When does that happen? Emacs does not cache the git diff output, so maybe passing HEAD verbatim into various commands should work just as well.

Here's how my code works (currently)
1. Get a concrete revision name (currently, this costs us one disk read to get the hash of head)
2. Produce an unmodified copy of the file in `/dev/shm` (or `/tmp` if no `/dev/shm` is found). This is very cheap as we prefer a ramdisk.
3. Diff the current buffer with the unmodified copy (producing another temp file in `/tmp`). This probably costs us one disk write.

On further diffs
1. Get a concrete revision name
2. Reuse the unmodified copy. (cached)
3. Diff the current buffer with the unmodified copy

> maybe passing HEAD verbatim into various commands should work just as well.

I would like to. Ultimately, I wish there were some sort of `(vc-diff (vc-working-revision buffer-file-name) (current-buffer))` magic that would simplify this, but I haven't found it.The difficulty arises from diffing with the current _buffer_ (i.e. not a file). We need to manually write it out somewhere. When we do, we can no longer rely on `vc` for diffing, because our temp file is not under version control. Without `vc`, `HEAD` loses its meaning.

> By the way, you should feel free to bring up various problems either at emacs-devel, or via M-x report-emacs-bug.

Yes. I'm looking into just becoming an emacs developer outright and contributing. First, I'm cooking up a ton of advice to prove that everything works (before I start breaking things).

**Comment by dgutov** [comment]
> The rev-parse, which is one of the more expensive operations in this system, costs 0.002s on my system, which I doubt will be a problem.

I'm pretty sure the diff operation will become the most expensive, at least on some files.

> Ultimately, I wish there were some sort of ... magic that would simplify this

`git diff` can use stdin: http://stackoverflow.com/a/18174051/615245. Until VC supports this kind of operation, this probably won't help us, though, but `diff` can do that as well.

> Yes. I'm looking into just becoming an emacs developer outright and contributing.

That's great, but filing some bugs and starting a discussion or two would be good starting steps in this direction.

> Now I need to make it pretty and fast.

And then, I guess, we'll have to make `diff-hl` somehow flexible in when/how to diff. That's not trivial, too.

**Comment by PythonNut** [comment]
> I'm pretty sure the diff operation will become the most expensive, at least on some files.

Probably. I just checked with some medium source files (~4000 lines) and the diff took about 0.002s, so there is room for it to outstrip the `rev-parse`, but not by terribly much.

> git diff can use stdin: http://stackoverflow.com/a/18174051/615245. Until VC supports this kind of operation, this probably won't help us, though, but diff can do that as well.

That's interesting. We'd need to forgo `diff-no-select` and write our own diffing procedure.

> That's great, but filing some bugs and starting a discussion or two would be good starting steps in this direction.

I have in the past. One bug was fixed quickly, and the other has not yet been touched by anyone. (And I can't fix it myself). I don't really know what to discuss, so I haven't done any of that.

> And then, I guess, we'll have to make diff-hl somehow flexible in when/how to diff. That's not trivial, too.

Right now, I've advised `dif-hl-changes`, and I run `diff-hl-update` with an idle-timer (it was actually working fine in the `post-command-hook`, but I chickened out of that). It's working pretty well so far, but if you have better ideas, I'm all ears.

**Comment by dgutov** [comment]
> We'd need to forgo diff-no-select and write our own diffing procedure.

Or update `diff-no-select` to use stdin when it can. You should measure the performance first, though: the temp file solution is probably fast enough anyway, especially if the user has an SSD.

> and the other has not yet been touched by anyone

What's the number? I can look at it, if it's within my competence (and interesting enough :)).

> I don't really know what to discuss, so I haven't done any of that.

If you intend to become an Emacs developer, surely you have some improvement to Emacs in mind? Or will you stop at this package?

> I've advised dif-hl-changes

That could be generalized with a `diff-hl-changes-function` variable...

> I run diff-hl-update with an idle-timer (it was actually working fine in the post-command-hook, but I chickened out of that)

Yeah, an idle timer is safer anyway.

> It's working pretty well so far, but if you have better ideas, I'm all ears.

Sounds like it might work fine as a new minor mode. Not sure yet if I want this to be the default behavior. But if that's all you needed to change, overall the necessary changes look pretty simple, which is good.

**Comment by PythonNut** [comment]
@dgutov Sorry, I meant to add the bug #, but I never got around to it. It's #19455, and it deals with some special `zsh` syntax that breaks `sh-mode` highlighting.

> If you intend to become an Emacs developer, surely you have some improvement to Emacs in mind? Or will you stop at this package?

I usually do, but I generally just go and write code and, when I get stuck, ask specific questions on emacs.stackexchange to help me along.

> Sounds like it might work fine as a new minor mode. Not sure yet if I want this to be the default behavior. But if that's all you needed to change, overall the necessary changes look pretty simple, which is good.

I have no problem with it being a custom variable or a minor mode.

> That could be generalized with a diff-hl-changes-function variable...

Yes please.

The one other thing that I've found is that `diff-hl` removes highlighting during editing only to have it restored later when my idle-timer fires. This makes for some blinking that is a little distracting. Obviously this makes sense without flydiffs but with them, it just gets in the way. How can I disable this?

**Comment by dgutov** [comment]
> #19455

I see, yeah it looks pretty niche to me. But if you'd like a pointer, `sh-syntax-propertize-function` should be the function to improve.

> How can I disable this?

With `(remove-hook 'after-change-functions 'diff-hl-edit t)`?

**Comment by PythonNut** [comment]
Okay, so summer is flying by. Here's my code, taken direct from my config. It's a bit of a mess, and I will clean it up, but I also don't want to let my absent-mindedness produce the possibility that I will forget this entirely.
```emacs
(defun diff-hl-make-temp-file-name (file rev &optional manual)
  "Return a backup file name for REV or the current version of FILE.
If MANUAL is non-nil it means that a name for backups created by
the user should be returned."
  (let* ((diff-hl-temp-location
           (if (file-directory-p "/dev/shm/")
             "/dev/shm/"
             temporary-file-directory))
          (auto-save-file-name-transforms
            `((".*" ,diff-hl-temp-location t))))
    (expand-file-name
      (concat (make-auto-save-file-name)
        ".~" (subst-char-in-string
               ?/ ?_ rev)
        (unless manual ".") "~")
      diff-hl-temp-location)))

(defun diff-hl-create-revision (file revision)
  "Read REVISION of FILE into a buffer and return the buffer."
  (let ((automatic-backup (diff-hl-make-temp-file-name file revision))
         (filebuf (get-file-buffer file))
         (filename (diff-hl-make-temp-file-name file revision 'manual)))
    (unless (file-exists-p filename)
      (if (file-exists-p automatic-backup)
        (rename-file automatic-backup filename nil)
        (with-current-buffer filebuf
          (let ((failed t)
                 (coding-system-for-read 'no-conversion)
                 (coding-system-for-write 'no-conversion))
            (unwind-protect
              (with-temp-file filename
                (let ((outbuf (current-buffer)))
                  ;; Change buffer to get local value of
                  ;; vc-checkout-switches.
                  (with-current-buffer filebuf
                    (vc-call find-revision file revision outbuf))))
              (setq failed nil)
              (when (and failed (file-exists-p filename))
                (delete-file filename)))))))
    filename))

(defun diff-hl-diff-buffer-with-head ()
  "View the differences between BUFFER and its associated file.
This requires the external program `diff' to be in your `exec-path'."
  (interactive)
  (vc-ensure-vc-buffer)
  (with-current-buffer (get-buffer (current-buffer))
    (let ((rev (diff-hl-create-revision
                 buffer-file-name
                 (vc-working-revision buffer-file-name
                   (vc-responsible-backend buffer-file-name)
                   t)))
           (temporary-file-directory
             (if (file-directory-p "/dev/shm/")
               "/dev/shm/"
               temporary-file-directory)))
      (if (called-interactively-p 'any)
        (diff rev (current-buffer) "-U 0" 'noasync)
        (diff-no-select rev (current-buffer) "-U 0" 'noasync
          (get-buffer-create " *diff-hl-diff*"))))))

(with-eval-after-load 'vc
  (defadvice vc-working-revision
    (around concrete-revision (file &optional backend concrete) activate preactivate compile)
    (setq ad-return-value
      (if concrete
        (vc-call-backend backend 'working-revision file t)
        (or (vc-file-getprop file 'vc-working-revision)
          (progn
            (setq backend (or backend (vc-responsible-backend file)))
            (when backend
              (vc-file-setprop file 'vc-working-revision
                (vc-call-backend backend 'working-revision file)))))))))

(with-eval-after-load 'vc-git
  (defadvice vc-git-working-revision
    (around use-hashes-only (file &optional concrete) activate preactivate compile)
    "Git-specific version of `vc-working-revision'."
    (if concrete
      (setq ad-return-value (vc-git--rev-parse ad-do-it))
      ad-do-it)))

(with-eval-after-load 'diff-hl
  (defvar diff-hl-modified-tick 0)
  (make-variable-buffer-local 'diff-hl-modified-tick)

  (setq diff-hl-draw-borders nil)

  (defadvice diff-hl-update
    (around flydiff (&optional auto) activate preactivate compile)
    (unless (and auto
              (or
                (= diff-hl-modified-tick (buffer-modified-tick))
                (file-remote-p default-directory)
                (not (buffer-modified-p))))
      ad-do-it))

  (defadvice diff-hl-changes
    (around flydiff activate preactivate compile)
    (setq ad-return-value
      (let* ((file buffer-file-name)
              (backend (vc-backend file)))
        (when backend
          (let ((state (vc-state file backend)))
            (cond
              ((or
                 (buffer-modified-p)
                 (eq state 'edited)
                 (and (eq state 'up-to-date)
                   ;; VC state is stale in after-revert-hook.
                   (or revert-buffer-in-progress-p
                     ;; Diffing against an older revision.
                     diff-hl-reference-revision)))
                (let (diff-auto-refine-mode res)
                  (with-current-buffer (diff-hl-diff-buffer-with-head)
                    (goto-char (point-min))
                    (unless (eobp)
                      (ignore-errors
                        (diff-beginning-of-hunk t))
                      (while (looking-at diff-hunk-header-re-unified)
                        (let ((line (string-to-number (match-string 3)))
                               (len (let ((m (match-string 4)))
                                      (if m (string-to-number m) 1)))
                               (beg (point)))
                          (diff-end-of-hunk)
                          (let* ((inserts (diff-count-matches "^\\+" beg (point)))
                                  (deletes (diff-count-matches "^-" beg (point)))
                                  (type (cond ((zerop deletes) 'insert)
                                          ((zerop inserts) 'delete)
                                          (t 'change))))
                            (when (eq type 'delete)
                              (setq len 1)
                              (cl-incf line))
                            (push (list line len type) res))))))
                  (setq diff-hl-modified-tick (buffer-modified-tick))
                  (nreverse res)))
              ((eq state 'added)
                `((1 ,(line-number-at-pos (point-max)) insert)))
              ((eq state 'removed)
                `((1 ,(line-number-at-pos (point-max)) delete)))))))))

  (defadvice diff-hl-overlay-modified
    (around preserve-overlays activate preactivate compile))

  (add-hook 'diff-hl-mode-hook
    (lambda ()
      (remove-hook 'after-change-functions #'diff-hl-edit t)))

  (run-with-idle-timer 0.3 t #'diff-hl-update t))
```

**Comment by dgutov** [comment]
Thanks for the update. It looks fine overall, but you've duplicated the temp-directory-finding logic once, and the `(called-interactively-p 'any)` bit looks odd.

**Comment by PythonNut** [comment]
> the `(called-interactively-p 'any)` bit is odd.

Ah yep, that's a side effect of some debugging I was doing a while ago. I've updated the code.

What should I do now?

**Comment by dgutov** [comment]
Should I send you the copyright assignment form now?

**Comment by PythonNut** [comment]
@dgutov sure, what do I need to do for that?

**Comment by dgutov** [comment]
Actually, forget about me sending, just follow these instructions:

http://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright/request-assign.future

Put in "Emacs" as the name of the program. It covers the packages in GNU ELPA as well.

**Comment by PythonNut** [comment]
Sorry, the process is taking a while...

One other benefit is that it would be really easy to grab saved/unsaved and even staged/unstaged diffs. I don't know how the UI would work, but, for example, we can diff unsaved changes by switching a single line.

**Comment by PythonNut** [comment]
Okay, the copyright assignment stuff is done. What happens now?

**Comment by dgutov** [comment]
Pull request seems to be in order. And in it, a new minor mode in a new file, as well as some changes to the existing code.

**Comment by Wilfred** [comment]
Thanks for putting this effort in! It'd be a great feature to have :)

**Comment by dgutov** [comment]
`diff-hl-flydiff-mode` has been merged into master.
