### ISSUE TITLE
Avoid starting diff-hl-mode in buffers without version control

### ISSUE THREAD

**Issue by duerrp** [dgutov/diff-hl#38]
Hi, great job with diff-hl!

I love the functionality so much that I want it to be active whenever possible. However, I don't want it to launch on buffers that are not associated with a file or buffers associated with files that are not in version control. 
Here's my workaround, maybe it helps other users:

```elisp
(defun custom-turn-on-diff-hl-mode ()
  "Turn on diff hl mode only if buffer is associated with file in version control."
  (interactive)
  (let ((bfname buffer-file-name))
    (when bfname
      (when (vc-backend bfname)
        (turn-on-diff-hl-mode))
      ))
  )
```

**Comment by dgutov** [comment]
Hi!

`global-diff-hl-mode` already doesn't turn `diff-hl-mode` in non-file (and non-vc-dir) buffers, see `turn-on-diff-hl-mode`.

Regarding files that are not in version control, why is that a problem? I don't think there's any perceptible performance regression caused by this mode. On the other hand, your code will omit newly-created and yet unregistered files even inside a version-controlled directory.

**Comment by duerrp** [comment]
Hi,

Thanks for the quick reply... I may be misunderstanding something, but when I activate `(global-diff-hl-mode)` without my custom function, I get the following error.

```
Debugger entered--Lisp error: (error "Buffer *scratch* is not associated with a file")
  signal(error ("Buffer *scratch* is not associated with a file"))
  error("Buffer %s is not associated with a file" "*scratch*")
  vc-deduce-fileset(nil t)
  vc-register()
  (if (not (eq (quote Git) (vc-backend buffer-file-name))) (vc-register) (shell-command (format "git add %s" buffer-file-name)) (message "Staged changes."))
  (lambda nil (interactive) (if (not (eq (quote Git) (vc-backend buffer-file-name))) (vc-register) (shell-command (format "git add %s" buffer-file-name)) (message "Staged changes.")))()
  eval-after-load-helper("/opt/emacs/share/emacs/24.4/lisp/vc/vc.elc")
  run-hook-with-args(eval-after-load-helper "/opt/emacs/share/emacs/24.4/lisp/vc/vc.elc")
  do-after-load-evaluation("/opt/emacs/share/emacs/24.4/lisp/vc/vc.elc")
  require(vc)
  eval-buffer(#<buffer  *load*-697482> nil "/home/peter/.emacs.d/elpa/diff-hl-20150113.2113/diff-hl.el" nil t)  ; Reading at buffer position 1766
  load-with-code-conversion("/home/peter/.emacs.d/elpa/diff-hl-20150113.2113/diff-hl.el" "/home/peter/.emacs.d/elpa/diff-hl-20150113.2113/diff-hl.el" nil t)
  (global-diff-hl-mode)
```

**Comment by dgutov** [comment]
This looks like a problem with your init directory. There must be an `eval-after-load 'vc` or `with-eval-after-load 'vc` form somewhere in it, and the code in it raises the error.

**Comment by duerrp** [comment]
You are right, the problem is in starter-kit-bindings.el.

Sorry for the trouble.
