### ISSUE TITLE
Fringe indicators when emacs is in daemon mode

### ISSUE THREAD

**Issue by manuel-uberti** [dgutov/diff-hl#40]
I am using latest version of diff-hl. I have ```(global-diff-hl-mode)``` in my init.

When starting Emacs in daemon mode, there are no indicators on the fringe. If I call ```(global-diff-hl-mode)``` twice (first disabling it, then enabling it back again), indicators appear.

Everything is working fine when using Emacs without daemon mode and with ```emacs -Q```.

I saw this problem was already fixed in issue [#2](https://github.com/dgutov/diff-hl/issues/2#issue-10584336), but as of today on Emacs ```25.0.50.1``` running on Debian unstable I am still experiencing the issue.

**Comment by dgutov** [comment]
Are you running Emacs in the terminal? Try `emacsclient -c`.

**Comment by manuel-uberti** [comment]
No, I am running with GUI using ```emacsclient -c```.

**Comment by dgutov** [comment]
Then please write down the precise steps for me to reproduce. It looks fine here.

**Comment by manuel-uberti** [comment]
Sure, this is what I do:

- add ```(global-diff-hl-mode)``` to my init.el
- start Emacs with ```emacs --daemon``` and ```emacsclient -c```
- open a file in a directory with a ```.git``` directory in it
- start editing the file
- save the file: no indicators on the fringe
- call ```M-x global-diff-hl-mode``` (diff-hl is now disabled)
- call ```M-x global-diff-hl-mode``` (diff-hl is now enabled)
- now indicators on the fringe are visible

**Comment by dgutov** [comment]
Nope, still works fine, in several Emacs version I've tried (24.3, `emacs-24` and `master`), on Ubuntu 14.10.

Try updating your Emacs to the latest `master`, or trying the 24.4 release. If everything fails, you're welcome to submit a patch.

But most likely, the problem is with your configuration: some other package could be interfering when launched in daemon mode.

**Comment by manuel-uberti** [comment]
Since it is working using ```(server-start)``` and you can't reproduce, you can consider this issue closed then. Thanks for the help and for the awesome package.

**Comment by dgutov** [comment]
No problem.
