### ISSUE TITLE
add update hook for "next" magit version

### ISSUE THREAD

**Issue by steckerhalter** [dgutov/diff-hl#41]
see: https://github.com/magit/magit/pull/1665/files

I think all it needs is:

```cl
        (add-hook 'magit-not-reverted-hook 'diff-hl-update nil t)
```

added to the mode definition

**Comment by dgutov** [comment]
Do we actually need to update in this case? The hook's description says it's run when the file has not changed on disk.

**Comment by steckerhalter** [comment]
yes, "not changed on disk" also means for example when the file has been comitted, so diff-hl needs to update. I'm not sure about the other hook, maybe it would also have to be added. I'll probably find out soon ;)

**Comment by dgutov** [comment]
Makes sense.

Do you know which version `magit-revert-buffer-hook` was removed in?

**Comment by steckerhalter** [comment]
as I understand it the current latest version is still based on master whereas the `next` branch (default branch on github) has been totally refactored and that's where the hooks change

so it might be possible that new versions based on `master` are released until they finally switch to the `next` branch

**Comment by dgutov** [comment]
At least one version was released from `master` recently: http://www.reddit.com/r/emacs/comments/314b56/magit_140_is_out/

Are you saying that hook was only removed on the `next` branch?

**Comment by steckerhalter** [comment]
I think so, yes. the pull request was merged into `next`

**Comment by dgutov** [comment]
But the pull request doesn't remove `magit-revert-buffer-hook`, it was removed sometime before.

Searching the `magit` repo doesn't find it anywhere in the code, so it was removed from `master` too.

**Comment by steckerhalter** [comment]
I checked locally, it's still in `master`:

https://github.com/magit/magit/blob/master/magit.el#L4075

**Comment by dgutov** [comment]
Hmm, thanks. It's weird that repository search doesn't find it.

**Comment by steckerhalter** [comment]
yes, kind of unreliable :smile:
