### ISSUE TITLE
Add `global-diff-hl-margin-mode`

### ISSUE THREAD

**Issue by dakrone** [dgutov/diff-hl#43]
Since there is both a `global-diff-hl-mode` and `global-diff-hl-amend-mode`, it would be great if there were a mode I could enable in the terminal (ie, `global-diff-hl-margin-mode`)

**Comment by dgutov** [comment]
`diff-hl-margin-mode` is a global mode. Have you tried using it like that?

**Comment by dakrone** [comment]
Oh I didn't know it was a global mode, I thought it was buffer-specific, I'll use that then, thanks!

**Comment by dgutov** [comment]
No problem. There's commentary in the `diff-hl-margin.el` header, recommending how to use it.
