### ISSUE TITLE
update state fail

### ISSUE THREAD

**Issue by zijianyue** [dgutov/diff-hl#44]
Sometimes diff-hl update edit state fails  after save file, I found that vc-state returns unregistered in such case, though the file is under svn control. 
I have to revert the file ,then diff-hl can update edit state successfully again.

**Comment by dgutov** [comment]
Could you post the backtrace? `M-x toggle-debug-on-error`.

**Comment by zijianyue** [comment]
There is no error, but diff-hl can't display the file edit state, I debuged the diff-hl-changes function and found vc-state return unregistered ,which leaded the problem I guess , but the real vc-state should be edited.


below is the backtrace when I debug
-------------------
 diff-hl-changes()
  (let ((changes (diff-hl-changes)) (current-line 1)) (diff-hl-remove-overlays) (save-excursion (goto-char (point-min)) (let ((--dolist-tail-- changes)) (while --dolist-tail-- (let ((c (car --dolist-tail--))) (progn (let* (... ... ... ...) (forward-line ...) (setq current-line line) (let ... ... ...))) (setq --dolist-tail-- (cdr --dolist-tail--)))))))
  diff-hl-update()
  run-hooks(after-save-hook)
  basic-save-buffer()
  save-buffer(1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)

**Comment by dgutov** [comment]
Without error, the backtrace doesn't tell anything useful.

If you can reliably reproduce the problem (`vc-state` erroneously returning `unregistered`), file a bug for Emacs, with step-by-step scenario.

**Comment by dgutov** [comment]
No progress here.
