### ISSUE TITLE
Right fringe

### ISSUE THREAD

**Issue by tuhdo** [dgutov/diff-hl#45]
Is it possible to use `diff-hl` on the right fringe, to avoid conflict with `flycheck` and `linum`?

**Comment by dgutov** [comment]
Linum uses the margin, not the fringe.

Is the conflict with Flycheck really a problem for you? Normally, I'd take care of the warnings, and only after pay attention to the diff indicators.

**Comment by tuhdo** [comment]
Yes, both solution conflict with either flycheck or linum. I want to integrate in Spacemacs, since others are having problem with `git-gutter`, but currently it has visual problem since `diff-hl` can only be used with left fringe and does not look clean out of the box to new users.

**Comment by dgutov** [comment]
`diff-hl` can also be used with either margin (turn on `diff-hl-margin-mode` and set `diff-hl-margin-side` to `right`). But if you prefer the fringe, I can add a setting for it too.

**Comment by tuhdo** [comment]
Thank you very much! Working nicely.

**Comment by dgutov** [comment]
No problem.
