### ISSUE TITLE
Fringe faces not working in latest Emacs snapshots

### ISSUE THREAD

**Issue by purcell** [dgutov/diff-hl#46]
For some reason the fringe background color is always white in the latest Emacs, at least using the fringe version of `diff-hl` -- the margin version works fine, showing green and red etc. I'm guessing this is an Emacs issue, but it's possible the `diff-hl` code needs to be modified, so I thought I'd mention it here.

**Comment by dgutov** [comment]
I'm almost always running the latest `master`, and I don't see anything like that.

Probably a bug in the NS port. Let me know if you find out anything definite.

**Comment by purcell** [comment]
Yeah, I just spent ages trying to pin it down. If I start Emacs up with `-Q` then I can get everything to work okay. The problems seems to be related to changing themes and/or restoring frames at startup via `desktop.el`. It's odd because `flycheck`'s fringe indicators show up with the correct colors. Very confusing.

**Comment by dgutov** [comment]
Is there any particular theme involved?

I don't use `desktop.el` often, so there problem could as well be OS-agnostic.

**Comment by purcell** [comment]
I see it with my `sanityinc-tomorrow` themes, which set the diff-hl faces explicitly. But it seems to only happen after restarting Emacs and letting desktop.el restore my frames. So I'm _guessing_ it's an interaction between the frame parameters and themes...

**Comment by purcell** [comment]
I found that other themes were working okay, so after some investigation I've started setting the `:foreground` for fringe faces to the desired color as well as the `:background`. Still don't really understand why that works or why it's necessary, but it works now, and this at least is not a `diff-hl` issue. Thanks for your help & patience.

**Comment by dgutov** [comment]
Thank you for the follow-up. Are you going to file a bug?

**Comment by purcell** [comment]
I don't know if this *is* a bug, or simply something I was doing wrong in my theme which just happened to work previously. I'm [not the only one](https://github.com/bbatsov/solarized-emacs/blob/master/solarized.el#L721-L724) now setting both `:foreground` and `:background` to the same value in fringe face definition, but it seems odd to me that this would be necessary. In my case, the "foreground" colour of the fringe bitmaps ends up being the `:foreground` of the `default` face from what I can tell. I confess that I don't really understand what's going on. :-)

**Comment by dgutov** [comment]
It sounds like you should be able to do that, especially if it works fine without desktop.el. Worth a report anyway.

> I'm not the only one now setting both :foreground and :background to the same value in fringe face definition

Not sure what you mean, the values are different there.

**Comment by purcell** [comment]
> It sounds like you should be able to do that, especially if it works fine without desktop.el. Worth a report anyway.

Ah, `desktop.el` was a red herring, and I eliminated it as a source of any problems. So I don't know if it's a bug that `fringe` faces use `:foreground` as their background colour. 

> Not sure what you mean, the values are different there.

Hmm, right. I think perhaps the foreground colour gets used as the fill colour of the fringe bitmap, which I suppose makes sense.

**Comment by dgutov** [comment]
> I think perhaps the foreground colour gets used as the fill colour of the fringe bitmap, which I suppose makes sense.

No. The foreground color is used for the picture, and the background color fills the rest. In our case, the foreground is used for the border, and the background is the filler.

**Comment by dgutov** [comment]
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21301

Was this it?

**Comment by purcell** [comment]
Ah yes, seems likely, right? :-)
