### ISSUE TITLE
diff-hl-mode and narrowing

### ISSUE THREAD

**Issue by michael-heerdegen** [dgutov/diff-hl#48]
Hi,

AFAIK, "diff-hl-mode" just ignores any narrowing in effect, which gives random results for highlighting.

Not only that highlighting in the fringe is incorrect when narrowing is in effect.  The current code can even freeze Emacs!

Yesterday, I had narrowed a buffer to a single defun and tried to edit it.  The file has around 10000 lines and around 100 change hunks.  Emacs got extremely sluggish; after inserting a character, Emacs got frozen for a few seconds.  With the internal profiler, I got to know that time was spend in redisplaying.  I typed M-: (overlay-lists) and found tons of overlays, all from diff-hl.  I think they where all concentrated in the narrowed part; it's normal that Emacs gets sluggish in such circumstances.  After "widen" the sluggishness immediately disappeared.  However, the sluggishness does not always appear after narrowing, it's somewhat random.

I guess there is not much more to do than to wrap some code (in "diff-hl-update" or so) in
```
(save-restriction (widen) ...)
```

Thanks!

**Comment by dgutov** [comment]
Thanks for the report, it should work fine now.

**Comment by michael-heerdegen** [comment]
Dmitry Gutov <notifications@github.com> writes:

> Thanks for the report, it should work fine now.

Thanks!
