### ISSUE TITLE
'diff-hl' have problem in init proccess

### ISSUE THREAD

**Issue by hypernovagama** [dgutov/diff-hl#52]
Debugger entered--Lisp error: (void-function diff-hl-global-mode-change)
  (diff-hl-global-mode-change)
  (custom-declare-variable (quote global-diff-hl-mode) (quote nil) (quote ("/home/ec2-user/.emacs.d/elpa/diff-hl-20150818.822$
 
Is it the problem with the new version?

**Comment by dgutov** [comment]
I don't see this problem.

Can you reproduce it starting with `emacs -Q`?

**Comment by hypernovagama** [comment]
It can boot up smoothly in that way.
Anyway, after I deleted my .emacs.d folder and cloned it again, everything goes well…
