### ISSUE TITLE
diff-hl now requires Emacs 24.4, but doesn't declare that

### ISSUE THREAD

**Issue by purcell** [dgutov/diff-hl#54]
I see that the (excellent) new `diff-hl-flydiff.el` uses `nadvice`, so `diff-hl` now technically requires Emacs 24.4. It should therefore have a corresponding entry in its `Package-Requires`. An alternative would be to distribute that as a separate package, but you might want to avoid that.

**Comment by dgutov** [comment]
Isn't there a way to avoid either? While `diff-hl-flydiff.el` may fail to compile in Emacs < 24.4, the rest of the package should still work fine.

I like both keeping compatibility with older Emacsen and bundling the related minor modes in one package.

**Comment by purcell** [comment]
Well, I guess that's an option, but the failed byte compilation looks pretty bad IMO. :-(

**Comment by purcell** [comment]
My point is mainly that it seems awkward to ship a package compatible with older Emacs versions, and then have to say, "well, it includes this extra useful part, but you won't be able to use that unless you have an even newer Emacs, and you can expect the byte compilation to fail if you don't." Better in that case to ship a separate add-on package, I reckon.

**Comment by dgutov** [comment]
How about the latest change? There's no error during byte-compilation in 24.3; just a few undefined-function warnings.

**Comment by purcell** [comment]
Looks good. I guess you could also do:

```
(unless (require 'nadvice nil t)
  (error ...))
```

**Comment by dgutov** [comment]
Sounds good.
