### ISSUE TITLE
Feature Request - Stage hunk

### ISSUE THREAD

**Issue by jschaf** [dgutov/diff-hl#55]
Is there a way to stage the current hunk?

**Comment by dgutov** [comment]
None, sorry.

We're using the VC package to interface with different VCSes, and it has no notion of staging area, so far. So it doesn't implement any kind of "stage hunk" command.

**Comment by dgutov** [comment]
There's no indication which hunks are staged and which aren't, either. Without it, being able to stage hunks and not seeing what's changed, would by inadequate anyway.

A command like [commit-patch](https://github.com/caldwell/commit-patch) is probably a better approach. If only it didn't depend on Perl...

**Comment by jschaf** [comment]
Ah, that makes sense.  I'm trying to recreate a workflow from git-gutter.

1. Make small change
2. Stage small change from buffer
3. Commit immediately

That workflow is a lot less heavyweight than magit-status.

I think the way to go is to pull the hunk info from diff-hl and then use magit for staging and commiting.

**Comment by dgutov** [comment]
Maybe you could write a package that would integrate them that way.

`diff-hl` itself won't depend on Magit.

**Comment by jschaf** [comment]
I understand, just thinking out loud.  I'll close this as the feature is outside the scope of diff-hl.

**Comment by arichiardi** [comment]
Stumbled upon this as I use hunk staging in ` git-gutter` many many times a day. This package offers more and I was evaluating if I could switch to it.

**Comment by dgutov** [comment]
I have to news to offer you here, but these are related discussions: https://github.com/dgutov/diff-hl/issues/34, https://github.com/dgutov/diff-hl/issues/71.
