### ISSUE TITLE
Kill revert buffer on quit?

### ISSUE THREAD

**Issue by kovrik** [dgutov/diff-hl#57]
Currently if you call `diff-hl-revert-hunk` and answer Y or N it calls `(quit-windows-on diff-buffer)` in the end:
https://github.com/dgutov/diff-hl/blob/master/diff-hl.el#L420

This keeps `*diff-hl*` buffer open.

Consider this to be changed to `(quit-windows-on diff-buffer t)` to kill the buffer.
Alternatively, we can introduce new var `diff-hl-kill-revert-buffer-on-quit` OR new hook `diff-hl-quit-hook` (as it is done in `ediff`).

**Comment by kovrik** [comment]
>you usually don't see them

If I call `diff-hl-revert-hunk` 6 times and then try to switch buffer, I see at least 6 `*diff-hl*<n>` buffers in the list.

**Comment by dgutov** [comment]
Good point. So apparently, most buffer-switching commands ignore buffer ephemerity  nowadays.

I still have to ask: don't you use `vc-revert`? If it had such a custom var, `diff-hl-revert-hunk` could reuse it.

**Comment by kovrik** [comment]
I can't find any var or hook in `vc-revert` that we can reuse.

So, my suggestion is to either always kill `*diff-hl*` buffer on quit or introduce new var.

**Comment by dgutov** [comment]
Ah, never mind, let's just always kill it. It's not that important an issue.

**Comment by kovrik** [comment]
Thanks! :)
