### ISSUE TITLE
Using right margin for display doesn't work with more than 1 window in terminal

### ISSUE THREAD

**Issue by morgado-jb** [dgutov/diff-hl#61]
When using the right side margin for diff symbol display with a vertical split window setup in the terminal, diff-hl only works for the file being displayed in the rightmost window.

The bug only appears in terminal mode, it works as expected in graphical Emacs.

```
(use-package diff-hl
  :ensure t
  :defer t
  :init
  (progn
    (setq diff-hl-side 'right)
    (global-diff-hl-mode)
    (diff-hl-margin-mode)
    (diff-hl-flydiff-mode)))
```

**Comment by dgutov** [comment]
Try putting this into your init file:

```
(setq-default right-margin-width 2)
```

**Comment by morgado-jb** [comment]
Hi, that doesn't work, but from your help, I did:
```
(add-hook 'window-configuration-change-hook
          (lambda ()
            (set-window-margins (car (get-buffer-window-list (current-buffer) nil t)) nil 2)))
```
And this works.
Don't know anything about elisp so I don't know why that works, but it's fine for me.

**Comment by dgutov** [comment]
> Hi, that doesn't work

Did you try restarting Emacs?

**Comment by morgado-jb** [comment]
Yes I did. But like I told you, the other option works fine, so I'll stick to that as a workaround. Thank you.

**Comment by dgutov** [comment]
Too bad, it works for me.

I'm happy you've found a workaround, of course. By the way, you can use `get-buffer-window` instead of `(car (get-buffer-window-list ...)`.
