### ISSUE TITLE
problems in diff-hl-dired.el, when directory contains files under RCS control

### ISSUE THREAD

**Issue by ouboub** [dgutov/diff-hl#62]
When I use dired mode to visit a directory which contains files under RCS control (and I even might now know about it), then I obtain the following error, and Emacs refuses to enter that directory.

I suggest to blacklist the RCS backend.

[dired-diff-bug.txt](https://github.com/dgutov/diff-hl/files/90742/dired-diff-bug.txt)

**Comment by dgutov** [comment]
Thanks. Like discussed, I've added a list of backends to ignore, in variable `diff-hl-dired-ignored-backends`.

**Comment by ouboub** [comment]
>>> "Dmitry" == Dmitry Gutov <notifications@github.com> writes:

   > Thanks. Like discussed, I've added a list of backends to ignore, in
   > variable diff-hl-dired-ignored-backends.

Ok, I just downloaded version 1.8.2. That version does not include the
new variable!?

**Comment by dgutov** [comment]
It's only in the GitHub version yet (distributed via MELPA). I'll push it to GNU ELPA soon, hopefully after #60 is also resolved.

**Comment by ouboub** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    On 01/15/2016 05:51 PM, Dmitry Gutov
      wrote:
    
    
      It's only in the GitHub version yet (distributed via MELPA).
        I'll push it to GNU ELPA soon, hopefully after #60
        is also resolved.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    Hm I have 
      
    
    (add-to-list 'package-archives
                 '("melpa" . "http://melpa.org/packages/") t)
    
    
    but package-list-packages only shows me version 1.8.2

**Comment by dgutov** [comment]
>  (add-to-list 'package-archives

What if you add `(require 'package)` before that?

**Comment by ouboub** [comment]
>>> "Dmitry" == Dmitry Gutov <notifications@github.com> writes:

   >> (add-to-list 'package-archives
   > What if you add `(require 'package)` before that?

That was/is my setting
(require 'package)
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)

(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)

But strangely enough today  package-list-packages shows me also the
melpa version, maybe it was my connection.

Now the elpa directory shows


diff-hl-1.8.1
diff-hl-1.8.1.signed
diff-hl-1.8.2
diff-hl-1.8.2.signed
diff-hl-20160114.1559

But the melpa version is used.

So everything is fine now.

bye
