### ISSUE TITLE
Add diff-hl-mark-hunk function

### ISSUE THREAD

**Issue by sriramkswamy** [dgutov/diff-hl#63]
Is it possible to add a `diff-hl-mark-hunk` function that just selects the current hunk when already in the middle of a hunk? I'm not sure how hard this is since I don't know elisp.

**Comment by dgutov** [comment]
Shouldn't be hard. But why?

**Comment by sriramkswamy** [comment]
Well, it's mostly my workflow. Currently I'm working on a parallel project but it's not necessary for it to be parallelized just yet. So I put in parallel constructs right now to save time (and incredibly frustrating changes that occur later) but I don't push these into the main repo. These tend to be commented out and every time I want to check the construct (some of which are one line, some of which span multiple lines) I uncomment them and once it passes the test, I comment them back.

It's just way easier to comment and uncomment by saying `diff-hl-mark-hunk` and `comment-dwim`. A bigger incentive for me is that I use `evil-mode` and this can just be mapped as text-object and various operators, including custom ones, can act on it. I was used to this when I was using Vim and the [vim-signify](https://github.com/mhinz/vim-signify) plugin. I recently switched to Emacs and just trying to replicate a few things.

**Comment by dgutov** [comment]
Makes sense. Does this work for you?

```el
(defun diff-hl-mark-hunk ()
  (interactive)
  (let ((hunk (diff-hl-hunk-overlay-at (point))))
    (unless hunk
      (error "No hunk at point"))
    (goto-char (overlay-start hunk))
    (push-mark (overlay-end hunk) nil t)))
```

**Comment by sriramkswamy** [comment]
Yes, it works.

Thank you! I'm closing this issue now.

**Comment by dgutov** [comment]
Thanks for checking, I've pushed it to master.

**Comment by sriramkswamy** [comment]
I updated using MELPA and this works.
