### ISSUE TITLE
Modeline indication if file has changes

### ISSUE THREAD

**Issue by mcraveiro** [dgutov/diff-hl#64]
Hi,

thanks for this extremely useful mode - I am now moving away from git gutter altogether. I'm afraid I'm still finding my way around diff-hl, so I got a newbie question for you. Back in the long gone svn days there used to be a utility that displayed a little circle in the modeline, providing a helpful indication if a file had changes[1]. It would be green for "no changes", red for "has changes" and blue for "new file" (IIRC).

Does diff-hl support something like this? It is a feature which unfortunately I rely on quite a lot. I don't necessarily need a "dot", just some kind of indicator on the modeline (e.g. red/green filename, an X, etc).

Many thanks for your work.

Marco

[1] I speak a little bit about this feature on this blog post; do a find for Git-emacs and you should see it. http://mcraveiro.blogspot.co.uk/2015/05/nerd-food-prelude-of-things-to-come.html

**Comment by dgutov** [comment]
Hi Marco,

> moving away from git gutter altogether

Was there anything particular that made you move? I hear many people still prefer it.

>  little circle in the modeline

To be able to use `diff-hl`, you need to have VC workin, right? One option would be to look at its mode-line element. Normally, it looks like this: `Git-master`. However, if the file has "edited" status, it has a colon inside: `Git:master`. Neither the presentation nor its position are really configurable, however.

If you like, I can turn `diff-hl-mode`'s lighter (which right now is an empty string) into a customizable variable. Then you'll be able to use any indicator in there, making the choice based on the value returned by `(vc-state buffer-file-name)`. But the position on the mode-line will still be fixed (among other minor modes).

Or you can customize `mode-line-format` yourself, and put the image wherever you want. In that case, it doesn't seem like you'll need any special support from `diff-hl-mode`.

**Comment by tzz** [comment]
I'd like a customizable lighter too.

**Comment by hisnawi** [comment]
me too

**Comment by dgutov** [comment]
All right, `diff-hl-lighter` is now a variable. Not sure how useful it's going to be, though, considering its position in the mode-line is among the other minor modes, and that's hard to change inside this mode (likely inappropriate anyway).

**Comment by dgutov** [comment]
Let me know if it's still missing something.
