### ISSUE TITLE
diff-hl-changes does not return anything if perl prints warning.

### ISSUE THREAD

**Issue by ptrv** [dgutov/diff-hl#66]
I had a bad `locale` setting and due to that perl was outputting a warning every time `perl` was run.

The warning was the following:

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LC_ALL = (unset),
    LANG = "en_DE.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

This error was at the beginning of `*diff-hl*` results buffer and I had no change overlays in the fringe.

After fixing my `locale`, `diff-hl` works again.

I am not sure about doing something to fix this but I report the bug in order to being aware that the `*diff-hl*` buffer parsing can fail if perl prints warnings.

**Comment by dgutov** [comment]
Why did, uh, Perl run?

**Comment by ptrv** [comment]
My project is using Git and Git uses perl internally I guess.

**Comment by dgutov** [comment]
All right, thanks. I don't see an easy fix for this, but if someone does, please let me know.

**Comment by ptrv** [comment]
Repro: Try setting your locale to something which your system does not support, go to a file that is tracked by Git, change file and then you see this message in `*diff-hl*`

**Comment by ptrv** [comment]
@dgutov I agree with not fixing it, but at least it's documented here.

**Comment by dgutov** [comment]
> at least it's documented here

Sure.

**Comment by dgutov** [comment]
@ptrv This has came up again in #67, and apparently `M-x vc-diff` doesn't suffer from this problem. But looking at its code, I don't see anything that changes the current locale or etc.

Any ideas?
