### ISSUE TITLE
On emacs 25.0.93 diff-hl-mode can't display file state in files under git control

### ISSUE THREAD

**Issue by zijianyue** [dgutov/diff-hl#67]

**Comment by dgutov** [comment]
Works for me.

What's the full output of `M-x emacs-version`?

**Comment by zijianyue** [comment]
GNU Emacs 25.0.93.1 (i686-w64-mingw32) of 2016-04-23
TortoiseGit 2.1.0.0 (C:\Program Files\TortoiseGit\bin)
git version 2.7.2.windows.1 (C:\Program Files\Git\bin; C:\Program Files\Git\mingw32\; C:\Program Files\Git\mingw32\etc\gitconfig; C:\ProgramData\Git\config)

**Comment by dgutov** [comment]
What's the value of `vc-git-program`?

**Comment by zijianyue** [comment]
vc-git-program is a variable defined in ‘vc-git.el’.
Its value is "git"

  This variable may be risky if used as a file-local variable.

Documentation:
Name of the Git executable (excluding any arguments).

You can customize this variable.

This variable was introduced, or its default value was changed, in
version 24.1 of Emacs.

**Comment by dgutov** [comment]
What does `(executable-find "git")` evaluate to?

**Comment by zijianyue** [comment]
"c:/Program Files/Git/cmd/git.exe"

**Comment by dgutov** [comment]
Hmm, ok. And does `M-x vc-diff` still work for you?

**Comment by zijianyue** [comment]
yes it works.BTW,diff-hl-mode works well on my emacs 24.5

**Comment by dgutov** [comment]
> diff-hl-mode works well on my emacs 24.5

It works just as well in my Emacs 25.0.93.4, albeit on GNU/Linux.

Could you try stepping through `diff-hl-changes` (with Edebug), so that we get a rough idea where it process fails?

After the `goto-char` call there, press `e` and evaluate `(buffer-string)`. The buffer contents should be a valid diff. The file should contain some changes first, of course.

**Comment by zijianyue** [comment]
evaluate  (buffer-string)  returned this:

#("perl: warning: Setting locale failed.\nperl: warning: Please check that your locale settings:\n	LC_ALL = (unset),\n	LC_MESSAGES = \"C\",\n	LANG = \"CHS\"\n    are supported and installed on your system.\nperl: warning: Falling back to the standard locale (\"C\").\n--- C:/Users/G00280~1/AppData/Local/Temp/KajbTb_cedet-global.el	2016-05-11 20:00:56.067954000 +0800\n+++ lisp/cedet/cedet-global.el	2016-05-11 20:00:45.179106100 +0800\n@@ -28,0 +29 @@\n+
\n@@ -68,0 +70,2 @@\n+			  ((eq texttype 'symbolname)
\n+			   \"s\")
\n" 0 503 (fontified nil))


I tested on my emacs 24.5, it returned this 

semantic-analyze-current-context: Cannot analyze buffers not supported by Semantic [2 times]
#("diff --git a/lisp/cedet/cedet-global.el b/lisp/cedet/cedet-global.el\nindex 2eaafcb..e169188 100644\n--- a/lisp/cedet/cedet-global.el\n+++ b/lisp/cedet/cedet-global.el\n@@ -28,0 +29,2 @@\n+\n+\n@@ -68,0 +71,2 @@ SCOPE is the scope of the search, such as 'project or 'subdirs.\"\n+			  ((eq texttype 'symbolname)\n+			   \"s\")\n" 0 315 (fontified nil))

**Comment by zijianyue** [comment]
I put (setenv "LC_ALL" "C") in my dotemacs ,and it works now

**Comment by dgutov** [comment]
That's great, but I wonder what `vc-diff` does that `diff-hl` doesn't, that it works without this setting.

**Comment by dgutov** [comment]
@zijianyue Do you see the Perl warning in the output of `vc-diff` when you don't set `LC_ALL`?

**Comment by zijianyue** [comment]
no warning

**Comment by dgutov** [comment]
Could you please try this patch?

```diff
diff --git a/diff-hl.el b/diff-hl.el
index 2aaabd4..aec911b 100644
--- a/diff-hl.el
+++ b/diff-hl.el
@@ -226,7 +226,8 @@
                diff-hl-reference-revision))))
 
 (defun diff-hl-changes-buffer (file backend)
-  (let ((buf-name " *diff-hl* "))
+  (let ((buf-name " *diff-hl* ")
+        (coding-system-for-read (vc-coding-system-for-diff file)))
     (diff-hl-with-diff-switches
      (vc-call-backend backend 'diff (list file)
                       diff-hl-reference-revision nil

```

**Comment by zijianyue** [comment]
the patch failed, the same warning LC_ALL = (unset)

**Comment by dgutov** [comment]
OK, then what about:

```diff
diff --git a/diff-hl.el b/diff-hl.el
index 2aaabd4..bf29988 100644
--- a/diff-hl.el
+++ b/diff-hl.el
@@ -226,7 +226,12 @@
                diff-hl-reference-revision))))
 
 (defun diff-hl-changes-buffer (file backend)
-  (let ((buf-name " *diff-hl* "))
+  (let ((buf-name " *diff-hl* ")
+        (coding-system-for-read (vc-coding-system-for-diff file)))
+    (if (memq system-type '(windows-nt ms-dos))
+        (setq coding-system-for-read
+              (coding-system-change-eol-conversion coding-system-for-read
+                                                   'dos)))
     (diff-hl-with-diff-switches
      (vc-call-backend backend 'diff (list file)
                       diff-hl-reference-revision nil

```

?

**Comment by zijianyue** [comment]
no, the problem of this patch is the same

**Comment by iquiw** [comment]
There is a difference between `diff-hl` and `vc-diff`.
The former sets `vc-git-diff-switches` to `nil`, while the latter uses default value `t`.
If  `vc-git-diff-switches` is manually sets to `nil`, `vc-diff` shows the same Perl warnings.

**Comment by dgutov** [comment]
@iquiw I see, thanks. When we need to pass any switches to `git diff`, we have to call `git difftool` instead, and that's where the warnings come (from the external `diff` program).

**Comment by dgutov** [comment]
This workaround should do, then. Someone please try it out.

```diff
diff --git a/diff-hl.el b/diff-hl.el
index 2aaabd4..cb8618a 100644
--- a/diff-hl.el
+++ b/diff-hl.el
@@ -244,6 +244,9 @@
             (with-current-buffer (diff-hl-changes-buffer file backend)
               (goto-char (point-min))
               (unless (eobp)
+                (when (looking-at "perl: warning: Setting locale failed")
+                  (search-forward "---" nil t)
+                  (forward-line 0))
                 (ignore-errors
                   (diff-beginning-of-hunk t))
                 (while (looking-at diff-hunk-header-re-unified)

```

**Comment by ptrv** [comment]
@dgutov The patch works. But wouldn't it better to set `vc-git-diff-switches` to the same value as `vc-diff-switches` instead? I tried it out and it worked too.

**Comment by dgutov** [comment]
@pttv Why? The value nil means "use the value of vc-diff-switches".

**Comment by ptrv** [comment]
@dgutov Yes, but there is not perl error when setting `vc-git-diff-switches` instead of `vc-diff-switches` (as @iquiw stated)

**Comment by dgutov** [comment]
Oh. I get it now, thanks. It seems like a bug in Emacs, but there's some idea behind it.
