### ISSUE TITLE
Error when calling (diff-hl-flydiff-mode 0)

### ISSUE THREAD

**Issue by phil-s** [dgutov/diff-hl#68]
It's certainly an edge case, but if you disable `diff-hl-flydiff-mode` without having enabled it, `diff-hl-flydiff-timer` is void when the mode calls `(cancel-timer diff-hl-flydiff-timer)`

I suggest the following in its place:
```
    (and (boundp 'diff-hl-flydiff-timer)
         (timerp diff-hl-flydiff-timer)
         (cancel-timer diff-hl-flydiff-timer))
```

**Comment by dgutov** [comment]
Thanks. It should be better now.
