### ISSUE TITLE
Not getting fringe outline on emacs 25

### ISSUE THREAD

**Issue by justbur** [dgutov/diff-hl#72]
I noticed with emacs 25 and the darktooth theme that I wasn't seeing anything for the diff-hl fringe indicators. I checked emacs 24.5 this morning, and they show up like this in this theme
![diff-hl](https://cloud.githubusercontent.com/assets/2208382/16626285/3a2e3dea-4376-11e6-9d8b-d13835774e58.png)

Notice the lack of a background. When I switch to a theme that defines the background like leuven, I get the outline and the background in 24.5 but only the background in 25. 

Here's 24.5
![leuven-24 5](https://cloud.githubusercontent.com/assets/2208382/16626435/db2b7d3e-4376-11e6-9944-abb59b8f96d5.png)
 
and here's 25
![leuven-25](https://cloud.githubusercontent.com/assets/2208382/16626441/e01c0ec6-4376-11e6-94c2-5bf741de8471.PNG)

I'm using windows at the moment if it matters

**Comment by dgutov** [comment]
https://github.com/emacsfodder/emacs-theme-darktooth/blob/master/darktooth-theme.el customizes faces used by this packages. Please report any problems resulting from this, [there](https://github.com/emacsfodder/emacs-theme-darktooth/issues).

**Comment by justbur** [comment]
@dgutov can you explain the difference in the leuven theme based on the version of emacs?

**Comment by dgutov** [comment]
@justbur I can't. To that, I'd have to look into how these themes are defined, etc.

But it works just fine here with Emacs 25 and the default theme (and also tango-plus, which I use most of the time).

**Comment by justbur** [comment]
Hm, after randomly deleting things in my custom.el file the problem went away. Thanks for the feedback. If I see it again, I'll try to be more systematic.
