### ISSUE TITLE
diff-hl-flydiff-mode breaks company-mode selection

### ISSUE THREAD

**Issue by endofunky** [dgutov/diff-hl#77]
Enabling `diff-hl-flydiff-mode` seems to break selecting completions in `company-mode`'s popup for me. When using keybinds to scroll through the popup completion window nothing happens. Repeated keypresses have rather erratic behaviour after that.

Currently I use the following workaround, but now sure if I'm missing something here? This obviously feels a bit suboptimal because it'll also remove sections from the fringe while completing.

```emacs-lisp
;; Workaround for flydiff breaking company-mode keybinds
(defun ts/disable-hl-flydiff-mode (&rest ignore)
  (diff-hl-flydiff-mode -1))

(defun ts/enable-hl-flydiff-mode (&rest ignore)
  (diff-hl-flydiff-mode t))

(add-hook 'company-completion-started-hook 'ts/disable-hl-flydiff-mode)
(add-hook 'company-completion-finished-hook 'ts/enable-hl-flydiff-mode)
(add-hook 'company-completion-cancelled-hook 'ts/enable-hl-flydiff-mode)
```

I also tried to add an advice to `company-select-next` and `company-select-previous` to call `hl-diff-update` but that also seems to breaks completion.

**Comment by dgutov** [comment]
I don't see that. How do I reproduce this exactly?

**Comment by endofunky** [comment]
Here are both, my company and diff-hl configs which cause it to break (without above's workaround:

```emacs-lisp
(use-package company
  :ensure t
  :diminish ""
  :config
  (global-company-mode)
  (setq company-idle-delay 0.2)
  (setq company-minimum-prefix-length 1)
  (setq company-echo-delay 0)
  (setq company-begin-commands '(self-insert-command))
  (setq company-show-numbers t)
  (setq company-tooltip-align-annotations t)
  (setq company-selection-wrap-around t)
  (setq company-minimum-prefix-length 2)

  (defun ts/check-expansion ()
    (save-excursion
      (if (looking-at "\\_>") t
        (backward-char 1)
        (if (looking-at "\\.") t
          (backward-char 1)
          (if (looking-at "->") t nil)))))

  (defun ts/tab-indent-or-complete ()
    (interactive)
    (if (minibufferp)
        (minibuffer-complete)
      (if (ts/check-expansion)
          (company-complete-common)
        (indent-for-tab-command))))

  (defun ts/evil-complete-lambda (arg)
    "Ignores passed in arg like a lambda and runs company-complete"
    (company-complete))

  (setq evil-complete-next-func 'ts/evil-complete-lambda)
  (setq evil-complete-previous-func 'ts/evil-complete-lambda)

  (define-key evil-insert-state-map (kbd "TAB") 'ts/tab-indent-or-complete)

  (define-key company-active-map (kbd "TAB") 'company-select-next)
  (define-key company-active-map (kbd "C-n") 'company-select-next)
  (define-key company-active-map (kbd "C-p") 'company-select-previous))

(use-package diff-hl
  :if window-system
  :ensure t
  :commands (diff-hl-mode diff-hl-dir-mode)
  :init
  (add-hook 'prog-mode-hook 'diff-hl-mode)
  (add-hook 'dired-mode-hook 'diff-hl-dired-mode)
  (add-hook 'org-mode-hook 'diff-hl-mode)
  (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh)
  :config
  (require 'diff-hl-dired)
  (require 'diff-hl-flydiff)

  (setq diff-hl-side 'right)
  (setq diff-hl-draw-borders t)

  (use-package fringe-helper
    :ensure t
    :config
    (fringe-helper-define 'ts/diff-hl-added    '(top repeat) "XXXXXXXX")
    (fringe-helper-define 'ts/diff-hl-modified '(top repeat) "XXXXXXXX")
    (fringe-helper-define 'ts/diff-hl-deleted  '(top repeat) "XXXXXXXX"))

  (defun ts/diff-hl-fringe-bmp-from-type (type _pos)
    (cl-case type
      (unknown 'question-mark)
      (change 'ts/diff-hl-modified)
      (insert 'ts/diff-hl-added)
      (delete 'ts/diff-hl-deleted)
      (ignored 'diff-hl-bmp-i)
      (t (intern (format "diff-hl-bmp-%s" type)))))

  (diff-hl-flydiff-mode t)

  (setq diff-hl-fringe-bmp-function 'ts/diff-hl-fringe-bmp-from-type))

```

**Comment by dgutov** [comment]
Could you bisect that to the exact thing that causes the problem?

**Comment by endofunky** [comment]
I tried to narrow it down further, but enabling `diff-hl-flydiff-mode` seems to generally cause that issue:

```emacs-lisp
(use-package diff-hl
  :if window-system
  :ensure t
  :commands (diff-hl-mode)
  :init
  (add-hook 'prog-mode-hook 'diff-hl-mode)
  :config
  (require 'diff-hl-flydiff)
  (diff-hl-flydiff-mode t))

(use-package company
  :ensure t
  :diminish ""
  :config
  (global-company-mode)
  (setq company-idle-delay 0.2)
  (setq company-minimum-prefix-length 2))
```

This still breaks the cursor keys for me.

Running Emacs 25.1 RC2 on OS X, btw.

**Comment by dgutov** [comment]
Sorry, still can't reproduce. Can you give me instructions that start with `emacs -Q`, and don't use `use-package` or the like?

**Comment by endofunky** [comment]
Hi, I did some more digging. It appears to have been an issue with my `evil-mode` configuration and it's working fine now, except for a minor UI issue where company-mode blanks out part of the fringe when the popup is open, but I'll post that over there. Thanks again.

**Comment by valignatev** [comment]
@endofunky Sorry for necroposting, but I stumbled across exactly the same issue. Tried to narrowing it down I realized that company works either without `diff-hl-flydiff-mode`, or without `evil-mode`. Do you remember what was the cause for you?

**Comment by valignatev** [comment]
Ok, my elisp knowledge was not enough to resolve this conflict, so I've implemented a nasty hack which switches evil to emacs-state during company popup and reverts it after popup disappears. I hope it's temporary, since it's really dirty, but it works:
https://github.com/valignatev/dotfiles/commit/d5bf2ce62c784c53bbe028198e91d8f68c924238
Maybe somebody will find this useful :woman_shrugging:

**Comment by dgutov** [comment]
@valignatev You can ask that somewhere in the Evil issue tracker, or at least in Reddit. Will probably get a better response.

**Comment by valignatev** [comment]
@dgutov Sure, that's exactly what I'm planning to do as soon as I have some time :) Will definitely link solution here. Thanks for suggestion :heart:
