### ISSUE TITLE
add support for customized diff-hl-margin characters

### ISSUE THREAD

**Issue by arronmabrey** [dgutov/diff-hl#78]
It would be nice if the `diff-hl-margin` characters could be customized/configured.
For example I prefer to use `"·"` over `"!"` to represent change.

Currently they are hard coded [here](https://github.com/dgutov/diff-hl/blob/f8ce39d157144ee4b22d386dd40673ea7f87ecd7/diff-hl-margin.el#L95-L97)
```elisp
  (cl-loop for (type . char) in '((insert . "+") (delete . "-")
                                  (change . "!") (unknown . "?")
                                  (ignored . "i"))
```

**Comment by dgutov** [comment]
Hi!

I've added a customizable variable for this.

**Comment by arronmabrey** [comment]
That was quick! Thanks so much!

**Comment by idoo** [comment]
@dgutov could you please add some example how I can use it?

**Comment by dgutov** [comment]
@idoo Have you tried `M-x customize-variable`?

**Comment by idoo** [comment]
yep, I did, but I guess it can be nice to have some examples in wiki/readme ;)

**Comment by dgutov** [comment]
I'm not a fan of long READMEs, to be honest.

Emacs is a self-documenting editor, and this variable has a pretty simple value.

**Comment by ianyepan** [comment]
I am having trouble changing the diff-hl-margin to characters. Right now they are just full background colors of the margin. I can see the symbol values as follows, but I don't know how to activate them:

```
diff-hl-margin-symbols-alist is a variable defined in ‘diff-hl-margin.el’.

Its value is
((insert . "+")
 (delete . "-")
 (change . "!")
 (unknown . "?")
 (ignored . "i"))
```

Right now my diff-hl margin looks like this (on both terminal and GUI Emacs):

![image](https://user-images.githubusercontent.com/36686900/206034772-4573547a-39b5-4b3c-93a8-b8e3ced3222b.png)

The screenshot also includes my diff-hl configuration, in case it helps anyone point out what I am doing wrong.

Thanks in advance: @dgutov @idoo @arronmabrey

**Comment by ianyepan** [comment]
Never mind, found out it was because my theme was setting the foreground and background to the same color.
