### ISSUE TITLE
Define :background attribute for diff-hl-* faces

### ISSUE THREAD

**Issue by danrharms** [dgutov/diff-hl#83]
Some themes do not specifically define the faces `diff-hl-change/delete/insert`.  In these themes the fringe indicators feature only the outline, not the background.  This is not as easy to see, and I find it less than attractive.

Would you consider defining by default the :background attribute of these faces, so that, unless overridden, the default display is more attractive?

I can submit a pull request if this is acceptable.

**Comment by dgutov** [comment]
I'm not sure what's up with those themes, but we do define the background.

It's either defined explicitly (in `(defface diff-hl-change`), or inherited from the parent face, for the other two faces. Have you tried reporting this to one of the said themes?

Is this a color-limited situation? I see `diff-removed` and `diff-removed` don't specify background colors of the current terminal doesn't support at least 88 colors.

**Comment by danrharms** [comment]
This is in a GUI, emacs 25.1.1 on linux.

I don't know what's up.  For me the :background of face diff-added is "unspecified" when I do a `C-h o diff-added`.  Only the :foreground is not "unspecified".  Therefore making the change I described (adding a :background to face diff-hl-insert) makes a big and noticeable difference.

**Comment by danrharms** [comment]
By the way, you are right that diff-hl-change is not affected, my observations affect only diff-hl-insert and -change.

My display definitely supports more than 88 colors.  Is `(display-color-cells)` the correct way to retrieve it?  For me this returns 16777216.  I am on CentOs 6.5 running xfce.

**Comment by dgutov** [comment]
> For me the :background of face diff-added is "unspecified"

Same here, but it shows up fine. "inherit" is specified, right? That's where it gets the value for the background from.

> Therefore making the change I described (adding a :background to face diff-hl-insert) makes a big and noticeable difference.

Then we won't inherit it anymore, and thus look worse on themes that don't redefine the `diff-` faces.

> Is (display-color-cells) the correct way to retrieve it? For me this returns 16777216.

Same here. And I'm using Ubuntu 16.04 with Unity.

Maybe the themes you are having trouble with change the background of these faces to the same color as the fringe?

**Comment by danrharms** [comment]
I reviewed some common color themes.  There are quite a few that redefine `diff-added` so that it lacks a :background attribute.  Some of these (grandshell, material, solarized, sanityinc-solarized) later define a :background for `diff-hl-insert/delete` so there is no ill-effect, but many do not.  (The ill-effect I refer to here is a fringe indicator in `diff-hl-mode` that is difficult to see and unsightly, IMO.)

A non-exhaustive list of themes that are "broken" in this respect (for `diff-hl-mode`):
 - darktooth
 - tangotango
 - tao-yin, tao-yang
 - tomorrow
 - ample-flat
 - flatland
 - gruvbox
 - gruber-darker
 - pomegranate-explosion
 - deep-blue
 - digitial-ofs1
 - dark-blue2
 - emacs-21
 - beige-diff
 - emacs-nw
 - julie
 - ld-dark
 - matrix
 - salmon-diff
 - taming-mr-arneson


It's a long list, some of them no longer maintained, and may be difficult or time-consuming to have diff-hl-insert/delete faces added with :background attributes.  

In the meantime, for anyone else who may be bothered by this, I came up with a snippet of code that I run after a theme has been loaded.  It examines the :background attribute and adds it, only if missing.  'sym' here refers to the symbol of the theme just loaded.

    (when (eq (face-attribute 'diff-hl-insert :background nil t) 'unspecified)
      (custom-theme-set-faces
       sym `(diff-hl-insert ((t (:background "green4" :foreground "green3"))))))
    (when (eq (face-attribute 'diff-hl-delete :background nil t) 'unspecified)
      (custom-theme-set-faces
       sym `(diff-hl-delete ((t (:background "red4" :foreground "red3"))))))

**Comment by dgutov** [comment]
Thanks. That seems like a good personal solution.

But if you (or anyone else having this problem) are using a theme that's still maintained, it would be good to report this issue as well.
