### ISSUE TITLE
"Marker does not point anywhere" error by undo

### ISSUE THREAD

**Issue by iquiw** [dgutov/diff-hl#84]
Calling `undo` with `global-diff-hl-mode` enabled throws error in some case.

Using the following _~/.emacs.d/init.el_.

``` emacs-lisp
(prefer-coding-system 'utf-8-unix)
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
(add-to-list 'package-selected-packages 'diff-hl)
(package-install-selected-packages)
(global-diff-hl-mode)
(setq debug-on-error t)
```

Open a Git controlled and modified file, select the line above modified line.

![diff-hl](https://cloud.githubusercontent.com/assets/238681/22426492/bfbf2ab2-e742-11e6-860b-f81a16fc080a.png)

Type <kbd>C-w</kbd> and <kbd>C-x u</kbd>.
Then "Marker does not point anywhere" error was thrown.

```
Debugger entered--Lisp error: (error "Marker does not point anywhere")
  primitive-undo(1 (("1\n" . 1) (#<marker in no buffer> . -2) (#<marker in no buffer> . -2) (#<marker in no buffer> . -2) (#<marker at 3 in test.txt> . -2) (#<marker in no buffer> . -2) (#<marker in no buffer> . -2) 3 (t 22671 19176 0 0)))
  undo-more(1)
  undo(nil)
  funcall-interactively(undo nil)
  call-interactively(undo nil nil)
  command-execute(undo)
```

Emacs 25.1 + diff-hl-20161102.1726

**Comment by dgutov** [comment]
Thanks for the report. That looks like a bug in `primitive-undo`, triggered by the specific configuration of overlays.

I'll see if I can isolate this. But feel free to beat me to it.

**Comment by dgutov** [comment]
https://debbugs.gnu.org/25599

**Comment by dgutov** [comment]
This is now fixed in Emacs master: https://github.com/emacs-mirror/emacs/commit/e17d6e2f6f0b7e33f16884bcb29b4d5f4433941b
