### ISSUE TITLE
Different faces for classic and margin mode

### ISSUE THREAD

**Issue by lepieru** [dgutov/diff-hl#87]
It will be nice if we could set a different faces for `diff-hl-mode` and `diff-hl-margin-mode`.

In my case, I would like to change the background of `diff-hl-insert`, `diff-hl-change` and `diff-hl-delete` faces without changing the margin background face.

**Comment by dgutov** [comment]
What about the `diff-hl-dired-` faces? What relationship would you like to see between them and the new margin faces?

**Comment by lepieru** [comment]
`diff-hl-` faces are used for `diff-hl-margin-mode` too. You can have a look at our problem ![here](https://github.com/m-cat/nimbus-theme/pull/25). Moreover, I note that the `diff-hl-dired-` faces are not applied when you use the margin mode.

May `diff-hl-margin-` faces could be created with an inheritance to the classic `diff-hl-` faces. This way, it will not break anything IMHO and could be customizable.

I could try to patch this if it's ok.

**Comment by dgutov** [comment]
That doesn't really answer my previous message.

`diff-hl-dired-` faces are also used in the margin. What should we do with them?

**Comment by dgutov** [comment]
> I could try to patch this if it's ok.

Unless you have a copyright assignment for Emacs on file, better not.

**Comment by lepieru** [comment]
> May `diff-hl-margin-` faces could be created with an inheritance to the classic diff-hl- faces.

It seems I have misunderstood your question but it was my answer.

I would like to see different faces applied if the margin mode is enabled (for `diff-hl` and `diff-hl-dired` too). Do you think there is a clean way do this? Maybe not.

**Comment by dgutov** [comment]
I decided to only add the margin faces for the three major states, which covers normal buffers, and also dired indicators except for `unknown` and `ignored` states.

Please let me know if that ends up being an actual problem (should `diff-hl-margin-unknown` still inherit from `dired-ignored`?)
