### ISSUE TITLE
No clean up of `diff-hl-dired-process-buffer`s

### ISSUE THREAD

**Issue by mrBliss** [dgutov/diff-hl#89]
In `diff-hl-dired-update` a new temporary buffer is generated and stored in the buffer-local variable `diff-hl-dired-process-buffer`. This happens every time you open a vc-enabled directory using `dired`. Unfortunately, this temporary buffer is never killed!

To give you an idea, after an `emacs-uptime` of ~3 days, I have 100 of these buffers open. You can easily check this yourself by evaluating the following snippet:
```elisp
(let ((total 0))
  (dolist (buf (buffer-list))
    (when (string-prefix-p " *diff-hl-dired*" (buffer-name buf))
      (cl-incf total)))
  total)
```

Even though the total memory occupied by these buffers is peanuts, I still don't like it when buffers are leaked,  and I therefore consider it a bug.

**Comment by dgutov** [comment]
Very well. This seems to do it.
