### ISSUE TITLE
When using tramp diff-hl mode complain when exiting because of hg process running

### ISSUE THREAD

**Issue by hisnawi** [dgutov/diff-hl#90]
When ssh-ing to the project through tramp, I see the diff-hl package has active processes (hg) and it won't highlight code or directories. Although hg works fine through tramp.

The other problem is when trying to exit emacs, it complains about these hg processes being active and wants confirmation to kill them. I have other processes the were active as well but they terminate gracefully (irony for example) by themselves and I only see the diff-hl ones when emacs asks for confirmation. 

I had (diff-hl-mode) only no (diff-hl-flydiff-mode)

**Comment by dgutov** [comment]
Does `vc-diff` work okay remotely too? (Try `C-x v =`).

**Comment by hisnawi** [comment]
Yes, VC works fine and show diffs (vc-diff) on remote server.

**Comment by dgutov** [comment]
Seems to work okay here, on a remote Trisquel GNU/Linux, with Git 2.3.5 and Hg 2.8.2.

Very slow, though, but that has always been my experience with Tramp.

**Comment by hisnawi** [comment]
wjhen trying to quit emacs you don't get a message saying hg is still having an active process caused by diff-hl?

**Comment by dgutov** [comment]
I don't.

**Comment by dgutov** [comment]
Any process should be finished by the time you close Emacs anyway, because `diff-hl` calls `hg diff` synchronously, inside `after-save-hook`, when you press `C-x C-s`. Until it finishes, Emacs doesn't go on to process further keyboard events.
