### ISSUE TITLE
Clipped diff-hl indicator on emacs master

### ISSUE THREAD

**Issue by kaushalmodi** [dgutov/diff-hl#94]
Hello,

I have been noticing this issue for a while now:

Below you see the same file buffer open in two windows.

![image](https://user-images.githubusercontent.com/3578197/28580444-8719c9ea-712d-11e7-9a92-0ec451dfbd9b.png)

The buffer sharing the left border with the frame left border shows the `diff-hl` indicators fine. The window on the right has the same buffer but its indicator is getting clipped.

*I have the new native support of line numbers enabled, but I see this issue with that off too.*

I do not do anything fancy with `diff-hl` setup; it's being used as it is:

```el
(use-package diff-hl
  :bind (:map modi-mode-map
         ("s-v" . hydra-diff-hl/body)
         ("C-c v" . hydra-diff-hl/body))
  :init
  (progn
    (defconst modi/diff-hl-mode-hooks '(emacs-lisp-mode-hook
                                        conf-space-mode-hook ;.tmux.conf
                                        markdown-mode-hook
                                        css-mode-hook
                                        web-mode-hook
                                        sh-mode-hook
                                        yaml-mode-hook ;tmuxp yaml configs
                                        c-mode-hook
                                        org-mode-hook)
      "List of hooks of major modes in which diff-hl-mode should be enabled.")

    (dolist (hook modi/diff-hl-mode-hooks)
      (add-hook hook #'diff-hl-mode))

    (defhydra hydra-diff-hl (:color red)
      "diff-hl"
      ("=" diff-hl-diff-goto-hunk "goto hunk")
      ("<RET>" diff-hl-diff-goto-hunk "goto hunk")
      ("u" diff-hl-revert-hunk "revert hunk")
      ("[" diff-hl-previous-hunk "prev hunk")
      ("p" diff-hl-previous-hunk "prev hunk")
      ("]" diff-hl-next-hunk "next hunk")
      ("n" diff-hl-next-hunk "next hunk")
      ("a" modi/add-change-log-entry-other-window-and-return "add change log entry")
      ("q" nil "cancel"))

    (add-hook 'dired-mode-hook #'diff-hl-dired-mode)))
```

---

The default fringe width is 8. If I do `(set-fringe-mode 10)`, the truncation goes away.. But if I save that and restart emacs, the truncation is back (and I checked that `fringe-mode` was still 10 after restart).

I don't understand the emacs display mechanisms, so don't know why this bug doesn't affect the window that shares the left margin with the frame.

Help?

**Comment by dgutov** [comment]
I'm also seeing something like this. Please report it to Emacs: it's most likely caused by a change in the core.

**Comment by kaushalmodi** [comment]
Oh well, need to figure out an `emacs -Q` recipe now :)

**Comment by dgutov** [comment]
Indeed. You don't have to avoid using `diff-hl` in that recipe, though. Only if Eli asks that specifically.

**Comment by kaushalmodi** [comment]
> Please report it to Emacs: it's most likely caused by a change in the core.

Done! [(Bug#27830)][1]

[1]: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27830

**Comment by kaushalmodi** [comment]
In the case you are not following the debbugs thread, here is the workaround:

```el
(use-package frame
  :defer t
  :config
  (progn
    (setq window-divider-default-places 'right-only) ;Default 'right-only
    ;; https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27830#20
    ;; Workaround on emacs 26+ to prevent fringe truncation. You need to use
    ;; either scroll bars or window dividers to prevent that.
    ;; I dislike the default face of `window-divider', so I customize that in my
    ;; `smyx-theme`.
    (setq window-divider-default-right-width 1) ;Default 6
    (window-divider-mode 1)))
```
The `diff-hl` fringe looks great again after that:

![image](https://user-images.githubusercontent.com/3578197/31180368-756136ce-a8ec-11e7-94db-edbce25751b8.png)
