### ISSUE TITLE
Can't run from vc-dir buffer?

### ISSUE THREAD

**Issue by mookid** [dgutov/diff-hl#95]
When the package is badly configured and is triggered in vc-dir-mode, `diff-hl-diff-goto-hunk` asks whether to save the \*vc-dir\*\<REPOSITORY\> buffer, which is usually not desired as a file.

The proper solution against this is to enable `diff-hl-mode` only in `prog-mode`.

Is it possible to protect the user against such a case?

The following diff seems to be enough:

``` diff
--- a/elpa/diff-hl-20170709.2000/diff-hl.el
+++ b/elpa/diff-hl-20170709.2000/diff-hl.el
@@ -350,7 +350,7 @@
 (defun diff-hl-diff-goto-hunk ()
   "Run VC diff command and go to the line corresponding to the current."
   (interactive)
-  (vc-buffer-sync)
+  (and (buffer-file-name) (vc-buffer-sync))
   (let* ((line (line-number-at-pos))
          (buffer (current-buffer)))
     (vc-diff-internal t (vc-deduce-fileset) diff-hl-reference-revision nil t)
```

**Comment by dgutov** [comment]
You're not supposed to turn on `diff-hl-mode` in non-file buffers.

Try using `global-diff-hl-mode` or ` turn-on-diff-hl-mode`.
