### ISSUE TITLE
Can diff-hl handle global hunks between multi files?

### ISSUE THREAD

**Issue by lukertty** [dgutov/diff-hl#97]
Its very nice if `diff-hl-next-hunk` and `diff-hl-diff-goto-hunk` can work between multi files in the same git repo, just like the `magit-status` do.

**Comment by dgutov** [comment]
> diff-hl-next-hunk ...

That would look rather weird to me, but I'd probably accept a patch if the behavior is hidden behind a user option.

> diff-hl-diff-goto-hunk

Would it call `vc-root-diff` to get the full repository diff? At the very least, it would be slower in larger projects. The answer is probably the same, but either way, you could write your own command that does it.

**Comment by lukertty** [comment]
You are right. And i write a small function to find next changed file in git. I post here for someone perhaps need.

```elisp
;;;###autoload
(defmacro cycle-values (var values)
  `(let ((i (cl-position ,var ,values :test 'equal)))
     (setq ,var (elt ,values (if (and i (< (1+ i) (length ,values))) (1+ i) 0)))))
;;;###autoload
(defun first-hunk-next-file ()
  (interactive)
  (let ((files (magit-git-lines "diff" "@" "--name-only")))
    (when (car files)
      (let ((current-file (magit-file-relative-name)))
        (find-file (expand-file-name (cycle-values current-file files) (magit-toplevel)))
        (goto-char (point-min)) (diff-hl-next-hunk)))))
```

**Comment by lukertty** [comment]
And the whole function can be this
```elisp
(define-advice diff-hl-next-hunk (:around (f &rest r) cycle)
    (set-transient-map
     (let ((map (make-sparse-keymap)))
       (define-key map "\\" #'first-hunk-next-file) map))
    (condition-case nil (funcall f r)
      (error (let ((p (point))) (goto-char (point-min))
            (condition-case nil (funcall f r) (error (goto-char p) (message "No hunk in this buffer")))))))

(global-set-key (kbd "C-\\") #'diff-hl-next-hunk)
```
