### ISSUE TITLE
File error: Searching for program, No such file or directory, hg

### ISSUE THREAD

**Issue by hisnawi** [dgutov/diff-hl#98]
When visiting a file in a project controlled by Mercurial and if Mercurial is not installed on the machine I get this error:

`File error: Searching for program, No such file or directory, hg
`

I narrowed it down to this line in my config:

`    (add-hook 'dired-mode-hook 'diff-hl-dired-mode)
`

**Comment by dgutov** [comment]
You can take avoid this error by removing `Hg` from `vc-handled-backends`.

**Comment by hisnawi** [comment]
I am not prof. in elisp. Could you give me the full syntax?

**Comment by hisnawi** [comment]
Also, would removing Hg from vc-handled-backends wont let me see diff-hl markers?

**Comment by dgutov** [comment]
For instance, you can use the Customize interface:

```el
M-x customize-variable RET vc-handled-backends RET
```

and modify its value there.

**Comment by dgutov** [comment]
> Also, would removing Hg from vc-handled-backends wont let me see diff-hl markers?

For Hg repositories? Yes and no. You can't see them anyway without Hg installed.

**Comment by hisnawi** [comment]
Sure, But assuming I have taken Hg out of the vc-handled-backends and kept that setting in my init.el file, and then I ran on a machine was same emacs setting that has Hg installed. Would I see the diff-hl markings or not?

**Comment by dgutov** [comment]
You will not, indeed.

**Comment by hisnawi** [comment]
Got it. Thanks.
