### ISSUE TITLE
diff-hl-flydiff with mercurial

### ISSUE THREAD

**Issue by djangoliv** [dgutov/diff-hl#99]
With mercurial, `diff-hl-flydiff-mode` does'nt work (can't see uncommitted changes in the fringe).
Moreover, diff-hf-mode stops working too.

Regards

**Comment by dgutov** [comment]
It work on my machine, with Emacs 26 snapshot and a mozilla-central checkout. It's not fast, though (that repo is pretty big).

**Comment by djangoliv** [comment]
Strange... I use Emacs 25.3.2 with 

```
(setq diff-hl-fringe-bmp-function 'diff-hl-fringe-bmp-from-type)
(require 'diff-hl)
(require 'diff-hl-flydiff)
(diff-hl-flydiff-mode)
(global-diff-hl-mode)
```
And no mark. If I comment (require 'diff-hl-flydiff) and (diff-hl-flydiff-mode) it works.
I use the mercurial evolve extension...  that may be the reason.

I will search.
Thanks

**Comment by dgutov** [comment]
> I will search

You can start with `emacs -Q -L ~/.emacs.d/siteelpa/diff-hl-...`.

**Comment by djangoliv** [comment]
I change the order in my configuration, and then it works. 
```
(setq diff-hl-fringe-bmp-function 'diff-hl-fringe-bmp-from-type)
(require 'diff-hl)
(global-diff-hl-mode)
(require 'diff-hl-flydiff)
(diff-hl-flydiff-mode)
```
Sorry for this issue and thanks for your time...
You can close it !

**Comment by dgutov** [comment]
Very weird.

I tested it with the first order in Emacs 25.2 (this morning), and it worked just as well.
